### PR TITLE
[beta] Accessibility update text colors

### PR DESCRIPTION
**Pull request by Arhell**
resolve https://github.com/reactjs/reactjs.org/issues/4916

### CODE REVIEW

**Comment by gaearon** [comment]
Can you please provide screenshots before/after for specific parts you changed? We'd also want to avoid hardcoding colors. If we need a new shade of blue, I think we should add it to the config. Thank you!

**Comment by Arhell** [comment]
> Can you please provide screenshots before/after for specific parts you changed? We'd also want to avoid hardcoding colors. If we need a new shade of blue, I think we should add it to the config. Thank you!

After the update, only 1 error remained

before



after
Screenshot_1

there it is not noticeable to the eye, but the Accessibility Insights for Web application no longer produces errors

**Comment by Arhell** [comment]
before
https://beta.reactjs.org/

after
https://beta-reactjs-gfgg4z7ad-fbopensource.vercel.app/

**Comment by gaearon** [comment]
we keep the colors in `colors.js` which is referenced from the tailwind config. would you mind adding a proposed color there and matching the existing naming scheme? thanks!

**Comment by Arhell** [comment]
> we keep the colors in `colors.js` which is referenced from the tailwind config. would you mind adding a proposed color there and matching the existing naming scheme? thanks!

Done, but locally for some reason the colors that are added do not work

**Comment by Arhell** [comment]
> we keep the colors in `colors.js` which is referenced from the tailwind config. would you mind adding a proposed color there and matching the existing naming scheme? thanks!

fix & update

**Pull request closed without merging**
