### PR TITLE
Add ReactiveConf

### PR DESCRIPTION
**Pull request by kristinavavrova**

### CODE REVIEW

**Comment by itchina110** [comment]
Website: https://react.w3ctech.com/

**Comment by gaearon** [comment]
Hi Kristína, thank you for the PR.

Though ReactiveConf is not a React-specific conference, we have featured ReactiveConf on this page in 2015, 2016, and 2017.

However, over time we’ve repeatedly received negative feedback from the React community about how it’s being organized. Here are some of the public examples:

* https://medium.com/@jevakallio/why-i-will-not-be-speaking-at-reactiveconf-6e106b3816a5
* https://medium.com/@peggyrayzis/why-i-cancelled-my-reactiveconf-talk-3a463bf14bd8
* https://mobile.twitter.com/gensym/status/957688073374060544
*  https://mobile.twitter.com/iamsapegin/status/960454824738349056

We’ve also received similar feedback in private.

We understand that mistakes and misunderstandings happen, even when everybody has the best intentions. In this case **the issue is not in the isolated examples above but rather in this being a consistent theme** with ReactiveConf.

We have decided to not feature ReactiveConf on our website this year, but we will be monitoring the feedback from the speakers and the attendees. If it is more positive this year, we will consider featuring it again next year.

Thank you for your work, and I’m sorry if this is frustrating.

**Comment by kristinavavrova** [comment]
Hi Dan,

Thanks for your response :)
I see your point. As we are still looking for improvements and obviously here is a space for it, can you recommend us any appropriate Code of conduct you consider good sticking to (except the general CoC)? 
Looking forward to hearing from you!

**Comment by gaearon** [comment]
As far as I'm aware http://confcodeofconduct.com/ is a good one.

**Comment by sophiebits** [comment]
Note that adding a code of conduct doesn't do anything unless you actually pay attention to it. In particular, you need to stop the sexist and harassing treatment of speakers and attendees that has been propagated by the organizers let alone any that might be coming from conference participants.

That is, you should:

1. Make sure ReactiveConf is an inclusive, supportive place by fixing the issues that have led people to feel hurt or excluded, then
2. Post a code of conduct reflecting your _actual_ policies (which at this point should be good) and be ready to enforce it. 

The steps aren't reversible; it doesn't work if you just write and post the code of conduct without following it.

Hoping you can make ReactiveConf a more welcoming place. Good luck!

**Comment by kristinavavrova** [comment]
Hello Dan & Sophie,

Thanks for your answers!
We will make our best this year to make ReactiveConf better than last year ;)

**Pull request closed without merging**
