### PR TITLE
Add PrimeReact to UI components list

### LINKED ISSUE #1179: Add PrimeReact to the Communty UI Components Page
I'd appreciate if you could consider adding PrimeReact UI Suite to;

https://reactjs.org/community/ui-components.html

PrimeReact: A rich UI component suite for React featuring 70+ open source components.

https://www.primefaces.org/primereact/

Thank you.

### PR DESCRIPTION
**Pull request by Niladri24dutta**
Fixes #1179 

- Add PrimeReact to UI components list in the community section.

### CODE REVIEW

**Comment by cagataycivici** [comment]
Thank you!!!

**Comment by Niladri24dutta** [comment]
@cagataycivici it's not merged yet though

**Comment by httpJunkie** [comment]
Hi, should this link be organized alphabetically like the rest?

**Comment by Niladri24dutta** [comment]
@httpJunkie if it's suggested then I can push the update

**Comment by cagataycivici** [comment]
When can we expect the merge and the deploy to live?

**Comment by alexkrolick** [comment]
Yes, can the list please remain sorted alphabetically?

**Comment by Niladri24dutta** [comment]
> 
> 
> Yes, can the list please remain sorted alphabetically?

Done the changes , Can you please review and merge?

**Pull request merged**
