### PR TITLE
Fix example indentation

### PR DESCRIPTION
**Pull request by lauriejones**
Addresses #1084

Not sure why having margin set on the `<pre>` causes the weird indentation, but moving the margin to a padding in the wrapping element fixes it, and is my preferred spacing solution.

Alternatively adding `display: block;` to the `<pre>` tag styling also fixes the issue, but I am not sure if we always want the pre/code elements to be block. Are they ever displayed inline?

**Update**
Adding `display: block;` to the `<pre>` tag styling may be the better solution as the examples appear to not always be rendered inside the `.gatsby-highlight` class

### CODE REVIEW

**Comment by iagomelanias** [comment]
> Not sure why having margin set on the `<pre>` causes the weird indentation, but moving the margin to a padding in the wrapping element fixes it, and is my preferred spacing solution.

Besides that, the class `gatsby-code-jsx` is being used both in `pre` and `code` elements. Removing the duplicate class in `code` element also resolves this issue. 

You can check this by comparing the [current html version](https://reactjs.org/docs/introducing-jsx.html) with a [previous working version](https://web.archive.org/web/20180704215846/https://reactjs.org/docs/introducing-jsx.html).

**Current**:
screen shot 2018-07-24 at 21 31 06

**Previous version**:
screen shot 2018-07-24 at 21 29 35

I'm not sure how this bug was introduced tho.

**Comment by gaearon** [comment]
Seems like this causes the highlighting to have margins. Can we avoid that?

screen shot 2018-07-25 at 2 32 29 am

Also, do we know what broke it?

**Comment by gaearon** [comment]
>I'm not sure how this bug was introduced tho.

Probably a package upgrade but I don't know which one.
Could be: https://github.com/reactjs/reactjs.org/commit/d9cd3e311f1bae4639db18bc42ec219f3bf1b6a0, https://github.com/reactjs/reactjs.org/commit/45a72f9e71ed5b71100ede3067d633b571205775, https://github.com/reactjs/reactjs.org/commit/242dbdd7cc6b6cf7fdc24aa3a7f6215cd737406e.

Want to investigate?

**Comment by iagomelanias** [comment]
Yes, i'm gonna take a look now. 🙂

**Comment by gaearon** [comment]
I merged a quick fix in https://github.com/reactjs/reactjs.org/pull/1087 but would still appreciate more info if there was a bug in some update or if we just relied on implementation detail. Thanks for finding the cause!

**Comment by DSchau** [comment]
@gaearon I think it's 26892808f4aaba7e1b0e58b63c87b4e3cdebf670 that caused the issue, specifically _probably_ updating gatsby-remark-prismjs.

Swapping to that exact commit demonstrates the issue, and is I believe the first commit to show the indentation regression.

**Comment by gaearon** [comment]
Thanks for checking. Do you think the new behavior was intentional?

**Comment by DSchau** [comment]
Can't answer that one! Pinning `gatsby-remark-prismjs` to `1.2.11` seems to be the root "fix," but I honestly think what you've already done in #1087 is probably just as good of a fix :)

**Comment by gaearon** [comment]
Can you find the `gatsby-remark-prismjs` commit that broke this?

**Comment by iagomelanias** [comment]
I believe it was this one https://github.com/gatsbyjs/gatsby/commit/6f565042b9c1f337356ef73eac0654411c8d19d9#diff-912e9bd2ec5f0fdf7da012659ea44444. By the commit name, it seems it's intentional.

**Pull request closed without merging**
