### PR TITLE
Add Kent Dodds's new Epic React course

### PR DESCRIPTION
**Pull request by thegoodsheppard**
Not looking for a T-Shirt. I'm in the course, it's good.

### CODE REVIEW

**Comment by thegoodsheppard** [comment]
Just signed CLA.

**Review by crypt096 — APPROVED** [review]

**Comment by thegoodsheppard** [comment]
Not sure if I'm the one that 's supposed to close this (apologies, newbie). Going ahead with it to see if it works.

**Comment by alexkrolick** [comment]
@thegoodsheppard it wasn't merged when you closed it. Now it is, thanks

**Comment by thegoodsheppard** [comment]
Thanks @alexkrolick!

**Pull request merged**
