### PR TITLE
fix typo in higher-order-components.md

### PR DESCRIPTION
**Pull request by awxiaoxian2020**
In my perception, this "to" should not be omitted. Adding it would make it clearer.

### CODE REVIEW

**Review by eps1lon — CHANGES_REQUESTED** [review]
they're being "passed a data prop" i.e. `<CommentList data />` and not "to a data prop" i.e. `<SomeComponent data={CommentList } />`

**Comment by awxiaoxian2020** [comment]
> they're being "passed a data prop" i.e. `<CommentList data />` and not "to a data prop" i.e. `<SomeComponent data={CommentList } />`

I think we should change the expressions. The grammar is not correct. The passive shouldn't have objects. You mean that "they are being `as` passed a `as` data prop"?

**Comment by eps1lon** [comment]
>  You mean that "they are being passed as a data prop"?

I mean that a `data` prop is being passed to them.

**Comment by awxiaoxian2020** [comment]
> > You mean that "they are being passed as a data prop"?
> 
> I mean that a `data` prop is being passed to them.

So why don't we change the expression like what you said?
The current doc is saying the opposite meanings. I think.

**Pull request closed without merging**
