### PR TITLE
Fix:-Fixed wrong debug command

### PR DESCRIPTION
**Pull request by Biki-das**
yarn debug-test is now deprecated in React package.json. It has been replaced by yarn test --debug.

Uploading Untitled.mp4…

### CODE REVIEW

**Review by eps1lon — APPROVED** [review]
Are these all mentions? Asking in case we have a fork under `beta/`

**Comment by Biki-das** [comment]
> Are these all mentions? Asking in case we have a fork under `beta/`

did not got what exactly you meant by mentions?

**Comment by eps1lon** [comment]
> did not got what exactly you meant by mentions?

Is the deprecated command used anywhere else?

**Review by harish-sethuraman — APPROVED** [review]
Thanks, I dont see any other occurrences of the same command in the repo 👍🏻

**Comment by Biki-das** [comment]
> Thanks, I dont see any other occurrences of the same command in the repo 👍🏻

yup, the same was on the issue template in the react repo too, and has been fixed https://github.com/facebook/react/pull/26171#event-8535225687

**Pull request merged**
