### PR TITLE
Mentioned that `value` is supported in `<select>`

### PR DESCRIPTION
**Pull request by phistuck**
Clarified the documentation.

### CODE REVIEW

**Review by eps1lon — APPROVED** [review]
Thanks!

**Comment by eps1lon** [comment]
@phistuck Could you sign this please? Otherwise I'd have to revert this PR.

New to this repo and I wasn't aware this was a required check.

**Comment by phistuck** [comment]
@eps1lon - hehe, slow bots are weird.
I signed it now. But I would not be surprised if they have an issue with my application.

**Comment by phistuck** [comment]
Weird, it is already in production.

**Pull request merged**
