### PR TITLE
Update the broken links in the Overview section

### PR DESCRIPTION
**Pull request by natenovielli**

### CODE REVIEW

**Comment by natenovielli** [comment]
Opened issue #3393

**Comment by natenovielli** [comment]
Deploy preview linked to the page that is being updated: https://deploy-preview-3394--reactjs.netlify.app/docs/perf

**Review by eps1lon — APPROVED** [review]
Thanks!

**Comment by eps1lon** [comment]
Oh and please sign the CLA once the bot mentions it to you. I forgot to wait for it, again :sweat:

**Pull request merged**
