### PR TITLE
Update gatsby package through yarn upgrade-interactive

### PR DESCRIPTION
**Pull request by emmafallancy**
This PR is meant to upgrade GatsbyJS to be able to get the latest update for `gatsby-react-router-scroll` that result into error in ScrollContext and causes the component to be unmounted. This will be able to resolve issue in #14

@bvaughn , I hope this helps :)

### CODE REVIEW

**Comment by bvaughn** [comment]
Can confirm this PR fixes the issue originally reported against Firefox and the cookies whitelist plug-in.

**Comment by emmafallancy** [comment]
@bvaughn yikes! interesting... I tried running the same command that you did like below:

```
rm -rf .cache
rm -rf node_modules
yarn install
yarn build
```

Somehow, I can run the build without any error 🤔 . I'll check further and update you on it 😄 Let me know if I miss anything from the command or any other situation that could lead to that error

**Comment by KyleAMathews** [comment]
I tried upgrading as well and it worked just fine. Perhaps install fail? Also that looks like our old duplicate GraphQLs friend :-|

Also FYI, I'm working soon on new testing infrastructure for Gatsby that'll build all example sites + a bunch of community sites including reactjs.org on every PR so we'll be making sure reactjs.org is always upgradable :-)

**Comment by bvaughn** [comment]
> Also FYI, I'm working soon on new testing infrastructure for Gatsby that'll build all example sites + a bunch of community sites including reactjs.org on every PR so we'll be making sure reactjs.org is always upgradable :-)

This is fantastic! I was thinking about this over the weekend, wishing we had infrastructure like that setup. 👏 Nice!

> @bvaughn I've tried the same steps that you mentioned before and there's no error happening on my side.

I will give it another try today!

**Comment by bvaughn** [comment]
Failed again for me locally. (Same error as above.)

Looking in `yarn.lock` I see:
```
graphql@0.10.5, graphql@^0.10.3, graphql@^0.10.5:
  version "0.10.5"
  resolved "https://registry.yarnpkg.com/graphql/-/graphql-0.10.5.tgz#c9be17ca2bdfdbd134077ffd9bbaa48b8becd298"
  dependencies:
    iterall "^1.1.0"

graphql@^0.11.3:
  version "0.11.7"
  resolved "https://registry.yarnpkg.com/graphql/-/graphql-0.11.7.tgz#e5abaa9cb7b7cccb84e9f0836bf4370d268750c6"
  dependencies:
    iterall "1.1.3"
```

And looking further for why this is, I see:
```
relay-compiler@1.3.0:
  dependencies:
    graphql "^0.10.5"

eslint-plugin-relay@^0.0.19:
  dependencies:
    graphql "^0.11.3"

gatsby@^1.9.9:
  dependencies:
    graphql "^0.10.3"
```

So the fix for me is to add another "resolution" to `package.json`:
```
  "eslint-plugin-relay/graphql": "0.10.5"
```

It's interesting though that you two _aren't_ seeing this behavior on a fresh install. Which Yarn version are you both using? (1.2.0 here.)

**Comment by bvaughn** [comment]
In the meanwhile, @emmafallancy, would you be willing to update this PR with the following change?
```diff
diff --git a/package.json b/package.json
index dbb60bb28..9adc56da2 100644
--- a/package.json
+++ b/package.json
@@ -9,7 +9,8 @@
   "resolutions": {
     "gatsby/graphql": "0.10.5",
     "gatsby/react": "16.0.0",
-    "gatsby/react-dom": "16.0.0"
+    "gatsby/react-dom": "16.0.0",
+    "eslint-plugin-relay/graphql": "0.10.5"
   },
   "dependencies": {
     "@gaearon/react-live": "1.7.1-with-safari-fix",
diff --git a/yarn.lock b/yarn.lock
index 466fa8040..a7cd0524b 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -4485,18 +4485,12 @@ graphql-skip-limit@^1.0.6:
   dependencies:
     babel-runtime "^6.26.0"
 
-graphql@0.10.5, graphql@^0.10.3, graphql@^0.10.5:
+graphql@0.10.5, graphql@^0.10.3, graphql@^0.10.5, graphql@^0.11.3:
   version "0.10.5"
   resolved "https://registry.yarnpkg.com/graphql/-/graphql-0.10.5.tgz#c9be17ca2bdfdbd134077ffd9bbaa48b8becd298"
   dependencies:
     iterall "^1.1.0"
 
-graphql@^0.11.3:
-  version "0.11.7"
-  resolved "https://registry.yarnpkg.com/graphql/-/graphql-0.11.7.tgz#e5abaa9cb7b7cccb84e9f0836bf4370d268750c6"
-  dependencies:
-    iterall "1.1.3"
-
 gray-matter@^2.1.0:
   version "2.1.1"
   resolved "https://registry.yarnpkg.com/gray-matter/-/gray-matter-2.1.1.tgz#3042d9adec2a1ded6a7707a9ed2380f8a17a430e"
@@ -5466,7 +5460,7 @@ items@2.x.x:
   version "2.1.1"
   resolved "https://registry.yarnpkg.com/items/-/items-2.1.1.tgz#8bd16d9c83b19529de5aea321acaada78364a198"
 
-iterall@1.1.3, iterall@^1.1.0:
+iterall@^1.1.0:
   version "1.1.3"
   resolved "https://registry.yarnpkg.com/iterall/-/iterall-1.1.3.tgz#1cbbff96204056dde6656e2ed2e2226d0e6d72c9"
```

**Comment by emmafallancy** [comment]
@bvaughn that's an interesting catch. Yup, I can update the PR to add `"eslint-plugin-relay/graphql": "0.10.5"` 😄 

I'm using `yarn 1.2.1`

**Comment by bvaughn** [comment]
Just updated to Yarn 1.2.1 myself and was able to `yarn build` successfully. That's interesting.

May still best to add this resolution for now, to avoid tripping up others? ☹️ 

In the meanwhile, I also added a note to graphql/graphql-js/pull/989

**Comment by emmafallancy** [comment]
@bvaughn interesting `yarn` is interesting 🤣 Thanks for the updates.

Based on the notes that you added at [graphql/graphql-js#989](https://github.com/graphql/graphql-js/pull/989), I think it is still best to add the resolution, since it used to occur before.

**Comment by bvaughn** [comment]
Agreed.

I also spoke with Lee out of band and I don't think that PR is going to land because it apparently doesn't *solve* the problem so much as it *moves* it.

**Comment by emmafallancy** [comment]
Hi @bvaughn, pardon for the delay. I've updated the `package.json` with the requested change on adding resolution. Please confirm that it's working fine on your end as well 😃 

I ran the same command and build succeeded without any error. 🙇

**Pull request merged**
