### PR TITLE
[WIP] Hooks Recipes

### PR DESCRIPTION
**Pull request by gaearon**
This doesn't actually have any content yet.

### CODE REVIEW

**Comment by acdlite** [comment]
Why "Hooks Recipes" instead of "Recipes"? It would be nice to have e.g. recipes for how to do stuff with Suspense at some point, too.

**Comment by gaearon** [comment]
For now I'm just keeping it colocated with Hooks docs so it seemed related. We don't use Hooks outside of Hooks docs yet. I think if we start using them, we'll want to switch the whole thing over (or else offer two versions of each article). I'd want to later break recipes out in separate pages (once per recipe) in their own category.

**Comment by gaearon** [comment]
In other words — by the time we ship Suspense for data fetching this page would be broken down into several anyway.

**Comment by threepointone** [comment]
Want to abandon this?

**Pull request closed without merging**
