### PR TITLE
docs: Improve "Thinking in React" for color-blind people

### PR DESCRIPTION
**Pull request by AElmoznino**
## What this PR does:
Updates an image and its alt-text in the "Thinking in React" section of the docs to make it accessible for people with color blindness. Kind of hard for color blind to see those colors - let's lead by example ☺️

**Before:**
before

**After:**
after

### CODE REVIEW

**Review by alexkrolick — APPROVED** [review]

**Comment by alexkrolick** [comment]
lgtm - @eps1lon ?

**Review by eps1lon — APPROVED** [review]
I love everything about this 👍🏻

**Comment by eps1lon** [comment]
Bonus points for anybody that converts this to actual HTML for even better a11y

**Comment by AElmoznino** [comment]
@eps1lon Do you by chance happen to know other sections of the docs that need a bit of a11y care? 🙂

**Comment by eps1lon** [comment]
> @eps1lon Do you by chance happen to know other sections of the docs that need a bit of a11y care?

I've never really looked into it for reactjs.org to be honest. Since a11y is a continuous process it's probably best to re-evaluate it occasionally. 

Though the docs are currently being rewritten so I would suggest you wait for https://github.com/reactjs/reactjs.org/issues/3308 to be completed.

**Pull request merged**
