### PR TITLE
fix: correct order of future conference dates content

### PR DESCRIPTION
**Pull request by techieeliot**
- Update markdown word placement
- Move June 2023 conference date behind May 2023 dates

### CODE REVIEW

**Comment by techieeliot** [comment]
✍️ Signed the CLA

Screen Shot 2022-11-30 at 11 55 19 AM

**Review by eps1lon — CHANGES_REQUESTED** [review]
Conferences are sorted by date descending so the previous order makes sense to me. Thanks for the suggestion though.

**Comment by techieeliot** [comment]
> Conferences are sorted by date descending so the previous order makes sense to me. Thanks for the suggestion though.

I should have included this screenshot earlier. 

The dates for upcoming conferences is chronological order. June 27 is wrongly placed before May, and chronologically it is last in the list @eps1lon

**Comment by techieeliot** [comment]
Thank you, @eps1lon!

**Pull request merged**
