### PR TITLE
added hyperlink for Netlify

### PR DESCRIPTION
**Pull request by nkalinos**
I thought it would be useful for some to link out to Netlify as I had to google it myself when reading the documentation.

### CODE REVIEW

**Review by samuei — APPROVED** [review]

**Comment by eps1lon** [comment]
@nkalinos Could you sign the contributor license agreement? Otherwise we can't merge this PR.

**Comment by nkalinos** [comment]
> @nkalinos Could you sign the contributor license agreement? Otherwise we can't merge this PR.

Hi there, sorry it took so long to sign the CLA.

**Comment by nkalinos** [comment]
@samuei @eps1lon sorry for the delayed CLA signing, is there anything I can do to move this baby change, forward?

**Review by eps1lon — APPROVED** [review]
Thanks!

**Pull request merged**
