### PR TITLE
[Beta] fix useMemo API doc error.

### PR DESCRIPTION
**Pull request by webpig**
Fix issue #5223

### CODE REVIEW

**Comment by gaearon** [comment]
does this sentence occur anywhere else in the doc?

**Comment by webpig** [comment]
> 

this sentence occur once in useMemo API doc,.

**Comment by webpig** [comment]
> does this sentence occur anywhere else in the doc?

this sentence occur once in useMemo API doc,.

**Review by arafatiqbal — APPROVED** [review]
Nice catch

**Review by hexiaokang — APPROVED** [review]

**Review by eps1lon — APPROVED** [review]
Thanks!

**Comment by kavinkuma6** [comment]
> does this sentence occur anywhere else in the doc?

@gaearon yes, please refer [this](https://github.com/reactjs/reactjs.org/issues/5212#issuecomment-1301686849)

**Pull request merged**
