### PR TITLE
fix the code block for createRoot typescript error

### PR DESCRIPTION
**Pull request by folt**
Improving the documentation will improve the developer experience and provide a solution for issues:
[React 18 - typescript gives an error when reproducing official Upgrade Guide](https://github.com/facebook/react/issues/24208)
[[Bug]: createRoot type error - TS2345](https://github.com/facebook/react/issues/24196)

### CODE REVIEW

**Comment by gaearon** [comment]
This is not a typescript example. We can add a separate typescript example below but we shouldn’t have invalid JS code as the only example.

**Review by gaearon — CHANGES_REQUESTED** [review]
The blog post is written with JS in mind. This is not valid JS. Let’s think of another way.

**Comment by folt** [comment]
> The blog post is written with JS in mind. This is not valid JS. Let’s think of another way.

I propose to add a block with an example for typescript. What do you think?

**Comment by gaearon** [comment]
This still seems confusing to me. It breaks the flow of the page (all other examples have Before/After, but not this one), and it's inconsistent with the previous one (different ID).

**Comment by gaearon** [comment]
I fixed it slightly differently. This doesn't fix all examples but should be enough for people to figure out how to do this.

**Pull request merged**
