### PR TITLE
PWA support added successfully #4526

### PR DESCRIPTION
**Pull request by dewanshDT**
- [x] service worker added
- [x] manifest file added
gatsby

### CODE REVIEW

**Comment by dewanshDT** [comment]
@harish-sethuraman please can you help me with unsuccessful checks

**Comment by harish-sethuraman** [comment]
```
error gatsby-plugin-manifest@4.11.0: The engine "node" is incompatible with this module. Expected version ">=14.[15](https://github.com/reactjs/reactjs.org/runs/5758858121?check_suite_focus=true#step:4:15).0". Got "12.22.10"
```

Seems like the node version of the lint analyzer is lower(`12.22.10`) than the actual expected 14 for the library

**Comment by dewanshDT** [comment]
What should I do?

**Review by gaearon — CHANGES_REQUESTED** [review]
I'm not sure we actually want to do this.

In the past I've seen very bad experiences with service workers, including cases where things were getting cached forever, and it was impossible to get them updated properly. I don't think we want to merge this in unless we understand very clearly what the tradeoffs are.

**Comment by dewanshDT** [comment]
@gaearon can you suggest me something else to work on

**Pull request closed without merging**
