### PR TITLE
Reduce Logo Size

### PR DESCRIPTION
**Pull request by webdesserts**
I was looking at an app generated from `create-react-app` when I noticed how large the logo svg was for how simple the shapes were. This pull request contains a manual rewrite of the svg version of the logo. The svg is now about 90% smaller. There was also a `logo-large.svg` that was used for the banner that I've brought closer to this version of the svg.

### New SVG (374B)
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="-11.5 -10.23174 23 20.46348">
  <title>React Logo</title>
  <circle cx="0" cy="0" r="2.05" fill="#61dafb"/>
  <g stroke="#61dafb" stroke-width="1" fill="transparent">
    <ellipse rx="11" ry="4.2"/>
    <ellipse rx="11" ry="4.2" transform="rotate(60)"/>
    <ellipse rx="11" ry="4.2" transform="rotate(120)"/>
  </g>
</svg>
```

### Original SVG (3.9KB)
For effect, I've expanded the `d` attribute so that every draw command is on a separate line.
```svg
<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 23 20.46348">
  <title>logo</title>
  <path fill="#61dafb" d="
    M18.9107,6.63257
    h0
    q-.36721-.126-.74042-.2333.06187-.25141.11441-.505
    c.56045-2.72064.194-4.91237-1.05739-5.63386-1.1998-.692-3.1621.02952-5.14394,1.75414
    q-.29293.2555-.57267.52554-.18727-.17951-.3811-.352
    C9.05257.3439,6.97066-.43316,5.72058.29046,4.52191.98436,4.16686,3.04489,4.67144,5.62322
    q.0753.383.17.76179
    c-.29458.08367-.57908.17284-.85127.26771
    C1.55514,7.50165,0,8.83225,0,10.21231
    c0,1.42546,1.66935,2.8552,4.20575,3.722
    q.3085.10494.62193.19442-.10179.408-.18068.82114
    c-.48106,2.53354-.10535,4.54521,1.09017,5.23484,1.23481.712,3.30725-.01985,5.32533-1.78387
    q.23926-.20917.47994-.44238.3029.29225.62173.56727
    c1.95477,1.68207,3.88531,2.36132,5.07982,1.66986,1.23369-.71416,1.63454-2.87525,1.114-5.50459
    q-.05955-.30124-.13792-.61481.21834-.06443.42772-.13355
    C21.28454,13.06915,23,11.65681,23,10.21232,23,8.82726,21.39478,7.48771,18.9107,6.63257
    Z
    M12.7284,2.75581
    C14.42646,1.278,16.01346.69457,16.73657,1.1116
    h0
    c.77014.44421,1.06971,2.2354.5858,4.58441
    q-.04758.22953-.10342.45724
    a23.53752,23.53752,0,0,0-3.07527-.48584
    A23.08128,23.08128,0,0,0,12.1995,3.24094
    Q12.45788,2.99184,12.7284,2.75581
    Z
    M6.79111,11.39124
    q.312.60265.65207,1.19013.34692.59911.7221,1.18117
    a20.92168,20.92168,0,0,1-2.11967-.3408
    C6.24867,12.766,6.49887,12.08443,6.79111,11.39124
    Z
    M6.79,9.08041
    c-.28613-.67863-.53093-1.34586-.73085-1.99019.65624-.14688,1.356-.26689,2.08516-.358
    q-.36611.571-.7051,1.15877
    Q7.10076,8.478,6.79,9.08041
    Z
    m.52228,1.15552
    q.45411-.94517.9783-1.8542
    v.0002
    q.52369-.90857,1.11521-1.77542
    c.684-.05171,1.38536-.07879,2.09432-.07879.71212,0,1.41437.02728,2.09819.0794
    q.58514.86487,1.10818,1.76941.52565.90635.99153,1.84545-.46083.94817-.98828,1.86173
    h-.0001
    q-.52261.90786-1.1034,1.7803
    c-.6824.04876-1.3876.0739-2.10623.0739-.71568,0-1.41193-.02229-2.08241-.06575
    q-.59555-.86995-1.12406-1.78305
    Q7.76789,11.18148,7.31227,10.23593
    Z
    m8.24853,2.33862
    q.347-.60182.667-1.21863
    h0
    a20.86671,20.86671,0,0,1,.77238,2.02327,20.85164,20.85164,0,0,1-2.14552.36573
    Q15.21935,13.16682,15.5608,12.57455
    Z
    m.65767-3.49343
    q-.31883-.605-.66163-1.19684
    h0
    q-.33727-.58258-.6994-1.15022
    c.7339.09263,1.437.21579,2.09717.36654
    A20.95909,20.95909,0,0,1,16.21847,9.08112
    Z
    M11.511,3.94359
    a21.01288,21.01288,0,0,1,1.3535,1.63393
    q-1.35843-.06419-2.7184-.00061
    C10.593,4.98765,11.0507,4.44022,11.511,3.94359
    Z
    M6.21284,1.14081
    c.76953-.44543,2.47095.18973,4.26428,1.782.11461.10179.22974.20836.34507.3186
    A23.54542,23.54542,0,0,0,8.86294,5.66608
    a24.008,24.008,0,0,0-3.06916.477
    q-.088-.35228-.15808-.70866
    v.0001
    C5.20339,3.22536,5.49044,1.559,6.21284,1.14081
    Z
    M5.09132,13.18233
    q-.286-.08187-.56778-.17773
    A8.32371,8.32371,0,0,1,1.841,11.57955
    a2.03072,2.03072,0,0,1-.85849-1.36724
    c0-.83742,1.24865-1.90571,3.33117-2.63178
    q.39208-.1361.79162-.24908
    a23.56455,23.56455,0,0,0,1.121,2.90478
    A23.92247,23.92247,0,0,0,5.09132,13.18233
    Z
    M10.41594,17.661
    a8.32161,8.32161,0,0,1-2.57467,1.61184
    h-.0001
    a2.03042,2.03042,0,0,1-1.61306.06067
    c-.72556-.41836-1.02706-2.03376-.61573-4.20035
    q.07337-.38407.168-.76363
    a23.10444,23.10444,0,0,0,3.0995.44869,23.90954,23.90954,0,0,0,1.97431,2.43929
    Q10.64,17.46459,10.41594,17.661
    Z
    m1.12223-1.11053
    c-.46569-.50253-.93015-1.05831-1.38383-1.65612
    q.66051.026,1.34566.02606.70326,0,1.38841-.03084
    A20.89425,20.89425,0,0,1,11.53817,16.55045
    Z
    m5.96651,1.367
    a2.03039,2.03039,0,0,1-.753,1.4278
    c-.72485.41958-2.275-.12581-3.94659-1.56431
    q-.2875-.24735-.57837-.52727
    a23.08914,23.08914,0,0,0,1.9279-2.448,22.93647,22.93647,0,0,0,3.11507-.48014
    q.07024.284.12449.55638
    h0
    A8.32,8.32,0,0,1,17.50468,17.91749
    Z
    m.83417-4.90739
    h-.0001
    c-.12571.04163-.25478.08184-.38629.12082
    a23.06121,23.06121,0,0,0-1.16468-2.91373,23.05112,23.05112,0,0,0,1.11938-2.87128
    c.23524.0682.46365.14.68372.21579,2.12842.73258,3.42665,1.81593,3.42665,2.65061
    C22.01753,11.10145,20.61538,12.25574,18.33885,13.0101
    Z"
  />
  <path fill="#61dafb" d="
    M11.5,8.1585
    a2.05386,2.05386,0,1,1-2.05381,2.05381
    A2.05381,2.05381,0,0,1,11.5,8.1585"
  />
</svg>
```

For some reason the github diff is rendering the two svgs in different sized containers, despite them both having the same sized viewbox, so here's the visual diff I was using:

**red**: old
**blue**: new
visual-diff-trimmed

### CODE REVIEW

**Comment by neauoire** [comment]
Excellent 👍

**Comment by neauoire** [comment]
Damn, that is one wasteful SVG.

**Comment by mjackson** [comment]
This looks fantastic! 😆  Strong work, @webdesserts! 💪 

This reminds me of the [Google logo redesign](https://design.google/library/evolving-google-identity/) where they reduced the size of the Google logo from ~14k => 305 bytes by using simpler shapes.

Thank you!

**Comment by bvaughn** [comment]
Love this cleanup! The old SVG was generated by Illustrator I guess, hence the complicated `path`.

I was wondering if we could clean it up a bit further and get rid of the awkward view box, aka:
```html
<svg viewBox="0 0 23 20" xmlns="http://www.w3.org/2000/svg">
  <title>React Logo</title>
  <circle cx="11.5" cy="10" r="2" fill="#fff"></circle>
  <g stroke="#fff" stroke-width="1" fill="transparent" transform="translate(11.5,10)">
    <ellipse rx="11" ry="4"></ellipse>
    <ellipse rx="11" ry="4" transform="rotate(60)"></ellipse>
    <ellipse rx="11" ry="4" transform="rotate(120)"></ellipse>
  </g>
</svg>
```

Would be nice to combine the white and normal variants too by just using `fill="currentColor"` and `stroke="currentColor"` but I'm not sure how we could make that work with the way they're being embedded in `` tags.

**Comment by bvaughn** [comment]
Hm. Looks like this got merged while I was writing my comment. 😄 I didn't know MJ was reviewing PRs here too. Welcome!

**Comment by mjackson** [comment]
Hey @bvaughn :D Sorry if I stepped on your toes here. I was a little trigger-happy with the merge button... 😅

**Comment by mjackson** [comment]
I also just pushed [another commit that uses `fill="none"` instead of `fill="transparent"`](e6eb004b28afd2353584d544e608c4d7ff6fcbdd) because it seems to be a little more widely supported. At least it works better for me when opening the svg in Sketch.

**Comment by webdesserts** [comment]
Btw, just to give credit where credit's due, I apparently wasn't the only one to do this, I later found that the logo on https://reasonml.github.io/reason-react/ isn't too far off from the logo proposed here.

**Comment by bvaughn** [comment]
No, not at all! I'm thrilled to have more active reviewers in this repo 😁

**Comment by webdesserts** [comment]
> I was wondering if we could clean it up a bit further

@bvaughn I actually had another version where the viewbox was a bit simpler, but decided to leave it alone for backwards compatibility. Both had the centered axis though. Now that I look at it, I didn't need the `cx` and `cy` fields, they should default to `0` when the axis is centered.

**Comment by bvaughn** [comment]
No worries. This is already a great improvement. 😄

**Comment by mbrevda** [comment]
according to the [spec](https://www.w3.org/TR/SVG/painting.html#StrokeWidthProperty), it seems that default value of `stroke-width` is `1`, making that prop redundant.

**Comment by webdesserts** [comment]
@mbrevda Nice, if we're golfing it a bit more, we could take that and a few of the changes mentioned above and bring it down to **324B**

```svg
<svg viewBox="-11.5 -10.25 23 20.5" xmlns="http://www.w3.org/2000/svg">
  <title>React Logo</title>
  <circle r="2" fill="#61dafb"/>
  <g stroke="#61dafb" fill="none">
    <ellipse rx="11" ry="4.2"/>
    <ellipse rx="11" ry="4.2" transform="rotate(60)"/>
    <ellipse rx="11" ry="4.2" transform="rotate(120)"/>
  </g>
</svg>
```

**Comment by sophiebits** [comment]
Hey -- this causes the hero buttons to be unclickable.

**Comment by webdesserts** [comment]
@sophiebits Oh geez! I'll publish a fix asap.

**Comment by sophiebits** [comment]
Fixed in #373.

**Pull request merged**
