### PR TITLE
update examples with Single page blog application

### PR DESCRIPTION
**Pull request by AaronMulgrew**

### CODE REVIEW

**Comment by AaronMulgrew** [comment]
No update? 🤔

**Comment by lex111** [comment]
@AaronMulgrew React version is quite old, you need to update it.

**Comment by AaronMulgrew** [comment]
> @AaronMulgrew React version is quite old, you need to update it.

I have now updated all libraries to latest.
Thanks

**Comment by gaearon** [comment]
Thanks, but the code formatting is inconsistent, and the example doesn't seem very instructive.

**Pull request closed without merging**
