### PR TITLE
added basic example of useState hook in functional component

### PR DESCRIPTION
**Pull request by krishnadevz**

### CODE REVIEW

**Comment by alexkrolick** [comment]
this is introduced later - this section is just reminding the reader of the ways to define function components 😄

**Comment by krishnadevz** [comment]
@alexkrolick can we push this thing as example code snippet .👋

**Comment by alexkrolick** [comment]
There are already several examples on this page, this area does not need one

**Comment by krishnadevz** [comment]
> 
> 
> There are already several examples on this page, this area does not need one

i think this one is a simple example that can help to the community that's why i made pull request and added example projects please go through 👉https://github.com/reactjs/reactjs.org/pull/2840

**Pull request closed without merging**
