### PR TITLE
Explain where act comes from

### PR DESCRIPTION
**Pull request by koba04**
I found this page when I search how to use `act()`, but this page didn't tell me where `act()` come from, so I had to search further to find out.

https://reactjs.org/docs/testing-recipes.html#act

I think adding the import statement is helpful for readers.

### CODE REVIEW

**Review by eps1lon — APPROVED** [review]
This is better than before. Technically it should mention that the `act` must be used from the corresponding renderer but if people copy this import and use the wrong `act` they get at least a descriptive error.

I'll follow-up with a note about different renderers.

**Review by eps1lon — CHANGES_REQUESTED** [review]
Actually the following tests include where this comes from. In this particular code section it isn't that important. What do you think about

```diff
- React provides a helper called `act()`
+ `react-dom/test-utils` provides a helper called [`act()`](/docs/test-utils.html#act)

**Comment by koba04** [comment]
@eps1lon 
> Actually the following tests include where this comes from. In this particular code section it isn't that important. What do you think about

That makes sense for me, so I've update my PR.

**Review by eps1lon — APPROVED** [review]
Thanks!

**Comment by koba04** [comment]
Thanks!

**Pull request merged**
