### PR TITLE
Migrate docs to hooks

### LINKED ISSUE #1788: Update docs to use hooks
As of now, the main docs haven’t been updated to account for hooks. Especially the state & lifecycle section seems a bit misleading now.

I’d love to help out with a rewrite, but I’d love to hear your feedback on what should be changed and what should stay behind.

### PR DESCRIPTION
**Pull request by nickmccurdy**
Fixes #1788 

This is a work in progress. I've converted most of the core documentation to use hooks, but I still need to test and update some examples. I'd still really appreciate feedback on how easy it is to learn with these documentation changes, and if there are any errors or inconsistencies.

Also please note that I'm not necessarily planning on removing the class documentation, it's just the easiest way to implement review these changes for now. I'm curious for suggestions about how to continue documenting classes, especially if it should be a separate legacy of the docs or a section specifically on classes (like the opposite of the current hooks section of the class docs).

## Tasks
- [x] Update internal files for home page
- [ ] Update internal files for docs
    - [x] Installation
    - [x] Main concepts
    - [x] Advanced guides
    - [ ] API reference
    - [ ] Hooks (new)
    - [x] Testing
    - [x] Contributions
    - [x] FAQ
- [x] Update external repositories
    - [x] Update React package documentation
        - [x] Readme
        - [x] Warning/error messages
    - [x] Update create-react-app template
- [x] Fix code highlighting
- [x] Search terms
    - [x] lifecycle
    - [x] render()
    - [x] class
    - [x] this.
- [x] Review state-and-lifecycle
- [ ] Dogfood (search class in src and remove)
- [ ] Merge hooks section content into main docs and migrate to classes (legacy)
- [ ] Update warning pages
- [ ] Update external example links (such as from CodePen and Gist)
- [ ] Integrate hooks tutorial

### CODE REVIEW

**Comment by nickmccurdy** [comment]
I’ve stopped working on this as it’s too much work for me alone to make the existing docs make sense for hooks, and the React team is planning on rewriting them from scratch anyway.

**Comment by karlhorky** [comment]
Thanks for the update Nick, too bad to hear, but understandable.

> the React team is planning on rewriting them from scratch anyway

Do you have a reference for this? Would like to follow along if possible.

**Comment by karlhorky** [comment]
@nickmccurdy Do you have any references for this React docs rewrite plan?

In the meantime, I've started to save your version to the Internet Archive, in case the Netlify deploy preview goes away for whatever reason:

https://web.archive.org/web/20200513121004/https://deploy-preview-2400--reactjs.netlify.app/docs/getting-started.html

https://web.archive.org/web/20200513121106/http://deploy-preview-2400--reactjs.netlify.app/docs/components-and-props.html

https://web.archive.org/web/20200513121122/http://deploy-preview-2400--reactjs.netlify.app/docs/state.html

**Comment by alexkrolick** [comment]
@rachelnabors is in charge of this on the React team side of things

**Comment by nickmccurdy** [comment]
FYI I plan on keeping my docs fork up at least until the official docs are updated. I don’t plan on keeping my docs up to date, but I’d be happy to accept contributions if others are interested in helping out.

**Comment by karlhorky** [comment]
Ah nice @nickmccurdy, do you think you could deploy it somewhere, just in case the Netlify deploy preview disappears?

I tried archiving it on the Internet Archive but apparently the links are already broken :(

**Comment by karlhorky** [comment]
And that's great Nick, thanks.

@rachelnabors, anywhere public that we can follow along with the conversion of the React Docs to use hooks?

**Comment by nickmccurdy** [comment]
@karlhorky It’s already deployed to Netlify. That’s a permanent deployment on their site, not just a preview.

**Comment by karlhorky** [comment]
Ah you mean that there's a different deploy somewhere than the PR deploy preview at https://deploy-preview-2400--reactjs.netlify.com ?

**Comment by karlhorky** [comment]
Ah maybe you mean this one here? https://reacthooks.nickmccurdy.com/

Sorry, just saw it on your repo now.

**Comment by karlhorky** [comment]
For anyone else looking, there is another version of the React docs with hooks here: https://reactwithhooks.netlify.app/

**Pull request closed without merging**
