### PR TITLE
HTTPS-ify most insecure URLs in content/docs (& one in Acknowledgments)

### PR DESCRIPTION
**Pull request by mgol**
This is a followup to #1157.

### CODE REVIEW

**Comment by lex111** [comment]
@mgol thank you! Safety in first place! :shield:

**Comment by tesseralis** [comment]
@mgol how were you able to verify that all the https links actually work? If you go to an https link that *isn't* actually secure, Google Chrome will tell you it's insecure and won't let you visit it.

**Comment by mgol** [comment]
@tesseralis I visited them all by hand in the browser. Well, not all URLs but at least one URL per domain (when I saw a repeated domain I didn't always check all paths).

**Comment by tesseralis** [comment]
Okay, thanks! Just wanted to make sure :)

**Pull request merged**
