### PR TITLE
Home page examples hooks and classes

### PR DESCRIPTION
**Pull request by Zeko369**
Upgrade Flow version and add a tab switcher to switch between hooks and class examples on homepage

Closes: #2833

### CODE REVIEW

**Comment by Zeko369** [comment]
The second example (`setInterval`) requires the use of useEffect, so I'd rather add a simple counter example (+, - buttons and a value) for the stateful example, add use this for "lifecycle" example.

Any ideas/comments?

**Comment by slk333** [comment]
a welcomed change that will probably require the approval of managers because it involves the frontpage of the website. Thank you for this pull request and i hope it will bring things forward!

**Comment by ImedAdel** [comment]
@gaearon Are you rewriting all the examples using hooks and functional components? 

I'd like to help if that's the case :) The tutorial, with classes, is a bit intimidating

**Comment by krishnadevz** [comment]
i just updated hooks section for useState in functional component if anyone is maintainer here they can merge/review my pull request here 👉https://github.com/reactjs/reactjs.org/pull/2842

**Pull request closed without merging**
