### PR TITLE
Linked to an example "from scratch" implementation

### PR DESCRIPTION
**Pull request by paradoxinversion**
@gaearon contacted me about adding a link my article on implementing react from scratch.  Let me know if anything needs to be changed.

### CODE REVIEW

**Comment by gaearon** [comment]
@paradoxinversion Can you please amend the article to include major versions explicitly when installing? This way your guide won't break when there's a new version of Babel etc.

**Comment by paradoxinversion** [comment]
@gaearon totally, I'll be able to make those edits within couple of hours. I also don't have any problems with keeping the article up-to-date in the future.

**Comment by alexkrolick** [comment]
ok great!

**Comment by paradoxinversion** [comment]
The article now targets specific versions when instructing folks to download packages: ie.` npm install --save-dev webpack@4.6.0 webpack-cli@2.0.14 ... `, and I've noted my node version in the first paragraph.

**Pull request merged**
