### PR TITLE
Add github repo link in the footer

### PR DESCRIPTION
**Pull request by arafatiqbal**
This adds the GitHub repo link in the footer, so it's easier to find, navigate to, and contribute

image
 
[Issue #5203](https://github.com/reactjs/reactjs.org/issues/5203)

### CODE REVIEW

**Review by eps1lon — COMMENTED** [review]
Makes sense to me but the misalignment is a bit unfortunate. Can you fix it to ensure these icons have are centered on the same horizontal axis visually?
Screenshot from 2022-10-29 10-24-48

**Comment by arafatiqbal** [comment]
@eps1lon Good catch, did not see that at all. Updated the svg to match the facebook one. 
image

**Review by eps1lon — APPROVED** [review]
Thanks!

**Comment by arafatiqbal** [comment]
Thank you for clarifying @gaearon

**Pull request merged**
