### PR TITLE
Use 16.8.2

### PR DESCRIPTION
**Pull request by gaearon**

### CODE REVIEW

**Comment by bvaughn** [comment]
(optimistic accept to unblock 😆)

**Comment by gaearon** [comment]
I was hoping for the bot comment but yours is also welcome

**Comment by bvaughn** [comment]
Kind of funny that the _actual_ version of React powering the docs website is still 16.7.0-alpha.0

**Comment by gaearon** [comment]
Wait what

**Comment by gaearon** [comment]
Lol. I thought we use one from CDN or something.

**Pull request merged**
