### PR TITLE
Include dynamic og image

### PR DESCRIPTION
**Pull request by harish-sethuraman**
We generate something like this and is dynamic for all beta pages. 
Checking if it works in PR preview

Screenshot 2022-04-22 at 11 25 20 PM

### CODE REVIEW

**Comment by harish-sethuraman** [comment]
This kind of partially works 

https://beta-reactjs-fd913dreb-fbopensource.vercel.app/api?title=Thinking%20in%20React&description=A%20JavaScript%20library%20for%20building%20user%20interfaces


We have to add complete URL with `window.location.origin` to show up in og:image I guess

**Comment by gaearon** [comment]
@lebo Do we want to have some design for og image shares? Like it could contain page title.

**Comment by lebo** [comment]
I think that could be cool. I do like GitHub's dynamic OG images.

**Comment by harish-sethuraman** [comment]
just a little hello requesting for design 😅  in case if this was missed

**Comment by lebo** [comment]
Ah, didn't know the action was on me. Here's a quick mock of a dynamic OG image with some basic metadata:

Option 2

Option 1

I didn't include the author but can add that in if that's necessary.

**Comment by gaearon** [comment]
can we get this working?

**Comment by harish-sethuraman** [comment]
https://beta-reactjs-6vc25hsv2-fbopensource.vercel.app/api?description=A%20JavaScript%20library%20for%20building%20user%20interfaces&amp;title=React%20Docs%20Beta

{"error":"Failed to launch the browser process!\n/tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n"}

Im quite unsure why this is happening in production and not in development? I've been looking for solutions to setup this in production. 
using this branch https://github.com/reactjs/reactjs.org/tree/add-dynamic-og-images as this PR came from forked repo and needs permissions sometimes for deploying

**Comment by harish-sethuraman** [comment]
I've seen services that provide these API's to all users. 
Like these 
`og-image` generator by vercel
https://og-image.vercel.app/**Hello**%20World.png?theme=light&md=1&fontSize=100px&images=https%3A%2F%2Fassets.vercel.com%2Fimage%2Fupload%2Ffront%2Fassets%2Fdesign%2Fvercel-triangle-black.svg

Github's `og:image` generator
https://opengraph.githubassets.com/cff3faac60aa54369c35c063e699d83de14536a2522c2ea2f485e52f12d4f966/reactjs/reactjs.org
try tweaking the org name and repo name alone and you should see the other repo's og:image

We can generate images for every page but that would have too many assets to maintain. Instead we could serve the og:image once and cache it forever? (Also we don't want to get spammed or constantly use compute power - we might want to find some other solution? 🤔 )

**Comment by gaearon** [comment]
Why is it a problem to have many assets in the repo? If they’re in a separate folder and don’t participate in the build process (they just lie around), I don’t see a downside.

**Comment by harish-sethuraman** [comment]
Fine then. Will write a script that runs during build to generate images.

**Comment by harish-sethuraman** [comment]
closing in favour of https://github.com/reactjs/reactjs.org/pull/5016

**Pull request closed without merging**
