### PR TITLE
Update languages page

### PR DESCRIPTION
**Pull request by tesseralis**
* Japanese is at 100%! おめでとう御座います！
screen shot 2019-03-01 at 4 29 45 pm

* Switch to just two categories: "complete" (100%) and "in progress" (<100%)
* Added new languages

Preview:
screen shot 2019-03-01 at 4 46 18 pm

The markdown styling feels a bit weird to me. Anyone have any ideas?

### CODE REVIEW

**Comment by gaearon** [comment]
What markdown styling?

Also, why do we change sections?

**Comment by bvaughn** [comment]
None of the partially translated docs for the in-progress languages are viewable after this change. Even ones like Portuguese (Brazil) that are well on their way.

**Comment by tesseralis** [comment]
@bvaughn ohh right that's why that section is there. Okay, reset everything to the old system for now. I'm still kind of iffy on the naming but that's a discussion we can have later. For now, let's make sure our page is updated :)

**Comment by bvaughn** [comment]
Pretty exciting to see zh-hans bumped up to 50%!

**Pull request merged**
