### PR TITLE
Comment to help user understand 'mountNode' on home page example.

### PR DESCRIPTION
**Pull request by craigdanj**
#1017 
This is to help users understand the mountNode variable on the home page of reactjs.org sicne currently it offers no explanation. This lack of an explanation might confuse users. 

eg: https://stackoverflow.com/questions/23600443/uncaught-referenceerror-mountnode-is-not-defined

### CODE REVIEW

**Comment by alexkrolick** [comment]
This is a good change, but the formatting in the front page code blocks is very narrow. Can you look at the deploy preview and figure out how to wrap the comment so it fits?

Thanks!

**Comment by alexkrolick** [comment]
Maybe we could pull the react-dom part into the home page examples plugin? Mountnode is defined there and needed to make the examples work with live edits.

**Comment by craigdanj** [comment]
@gaearon I actually like your idea better than mine. I agree mine isn't the best solution.

Can we replace 'mountNode' with

document.getElementById('root')

In all the examples? Would that make sense?

**Comment by gaearon** [comment]
I think it will be confusing to have `root` in several examples since IDs are supposed to be unique. But if you give each container a different ID (e.g. `simple-component`, `todo-app`, etc) then it will make sense.

**Comment by craigdanj** [comment]
@gaearon I've updated the first example to use ``first-component``. I figured if I add ``simple-component`` it'll look like I'm rendering the helloWorld component to a simple component when it actually is itself the simple component. Let me know what you think.

**Comment by craigdanj** [comment]
@gaearon Ok so I've updated all the examples to use getElementById() and have used ids that correspond to each example's title (like you suggested) since this makes more sense for the documentation.

Let me know if the naming is appropriate and if there is anything else I need to change since the main website has live code editing.

**Comment by gaearon** [comment]
I did something similar in https://github.com/reactjs/reactjs.org/pull/1526. I couldn't merge this PR because it didn't actually work, but thanks for starting it!

**Pull request closed without merging**
