### PR TITLE
Removed createBlockingRoot API docs and added a warning note

### PR DESCRIPTION
**Pull request by bvaughn**
Follow up to https://github.com/facebook/react/issues/21316

### CODE REVIEW

**Comment by eps1lon** [comment]
Want to remove `timeoutMS` as well while you're at it (https://github.com/facebook/react/pull/19703)? :smile:

**Comment by bvaughn** [comment]
Nope :D

**Comment by eps1lon** [comment]
> Nope  Sorry this was just a quick bandaid fix

Ok, I just looked for every mention of `timeoutMS` and it does look a bit more involved. I don't know enough about the current semantics to update sections such as

> If we make our API responses take 5 seconds, [we can confirm](https://codesandbox.io/s/relaxed-greider-suewh) that now React "gives up" and transitions anyway to the next screen after 3 seconds. This is because we passed `{timeoutMs: 3000}` to `useTransition()`. For example, if we passed `{timeoutMs: 60000}` instead, it would wait a whole minute.

**Review by gaearon — APPROVED** [review]
Seems fine but a lot of other things are outdated too so I don’t know that this one needs special treatment

**Comment by bvaughn** [comment]
True! I only proposed this because it seemed to cause confusion but I don't feel strongly one way or another.

**Pull request merged**
