### PR TITLE
Update constant name in useImperative example

### PR DESCRIPTION
**Pull request by Nightrider0098**
User Imperative example has to same ref name in child and in the parent. Causing confusion while understanding the concept. 

`function FancyInput(props, ref) {
  const **inputRef** = useRef();
  useImperativeHandle(ref, () => ({
    focus: () => {
      inputRef.current.focus();
    }
  }));
  return <input ref={**inputRef**} ... />;
}
FancyInput = forwardRef(FancyInput);`

`In this example, a parent component that renders <FancyInput ref={**inputRef**} /> would be able to call inputRef.current.focus().'

### CODE REVIEW

**Comment by Nightrider0098** [comment]
@sunny  minor pr, can you please look into it?

**Comment by sunny** [comment]
Wrong @sunny I think :)

**Comment by Nightrider0098** [comment]
> Wrong @sunny I think :)

updated my comment. can you pls review again?

**Comment by Nightrider0098** [comment]
@sunny shall I close the pr if the change suggested are wrong?

**Comment by sunny** [comment]
What I meant by “Wrong @sunny” is that you mentioned me, but I am not a reactjs.org maintainer.

**Comment by Nightrider0098** [comment]
@gaearon can you pls review the pr?

**Pull request closed without merging**
