### PR TITLE
Make error message bold on the decoder page

### PR DESCRIPTION
**Pull request by gaearon**
Maybe this will make it a bit more visible?
Inspired by https://github.com/facebook/react/issues/12119

### CODE REVIEW

**Comment by gaearon** [comment]
I think maybe it's a bit less elegant but it's more visible. I like it.

screen shot 2018-02-04 at 9 32 45 pm

**Comment by alexkrolick** [comment]
Maybe move the error above the fine print?

**Comment by gaearon** [comment]
I'm not sure how to do it without making the layout weird. (e.g. giant intro text shouldn't come after the error)

Happy to review a separate PR that does it though.

**Comment by gaearon** [comment]
I'm digging this:

screen shot 2018-02-04 at 22 37 45

**Comment by alexkrolick** [comment]
Yeah, that's fine too.

**Pull request merged**
