### PR TITLE
Rename "functional component" to "function component"

### PR DESCRIPTION
**Pull request by gaearon**
Related to discussion in https://mobile.twitter.com/getify/status/993127777057550336

Yay or nay?

### CODE REVIEW

**Comment by alexkrolick** [comment]
"Function component" sounds wrong grammatically. What about "component function"?

**Comment by gaearon** [comment]
We do say “class component” so I don’t think it’s too different. Just a bit unusual.

**Comment by gaearon** [comment]
Like “strawberry ice-cream”.

**Comment by alexkrolick** [comment]
Ok, as long as you stick to the ice cream analogy 😉

**Comment by sebmarkbage** [comment]
How are they not functional? They have to be pure. Are supposed to be used with lazy evaluation in a monadic way.

Even with state they are pure because the state will be based on algebraic effects.

If anything not calling them functional is misleading since they follow a strict set of rules that all come from functional programming. Everything is functions, including classes.

**Comment by gaearon** [comment]
>Everything is functions, including classes.

That's the point, isn't it?

It's not that function components aren't functional-by-nature. It's that they're indeed *all* functional, including classes. Therefore saying "functional" to mean "a component that happens to be a function, as opposed to a class" doesn't mean as much sense. But that's exactly how we use the term right now, and what this PR could change.

This doesn't mean either of them stop being functional. Just that we can might prefer to use the word "functional" to mean the paradigm and overall approach, rather than the component definition syntax.

Tbh I can argue both ways for this.

**Comment by gaearon** [comment]
(Chatted with @sebmarkbage and he's not opposed)

**Pull request merged**
