### PR TITLE
Introducing the new profiler

### PR DESCRIPTION
**Pull request by bvaughn**
# [View the formatted blog post](https://deploy-preview-1176--reactjs.netlify.com/blog/2018/09/10/introducing-the-react-profiler.html)

### CODE REVIEW

**Comment by sophiebits** [comment]
Idea: can we embed a live profiler demo in the post? (Just a iframe to now.sh or w/e so it isn’t a maintenance burden.)

**Comment by bvaughn** [comment]
That...is a pretty cool idea. Maybe! I'll play around with it.

**Comment by bvaughn** [comment]
I think I'll push a profiling-capable demo to now and share as a link with folks, but separately from the Blog post. That seems like a reasonable compromise.

**Comment by bvaughn** [comment]
http://react-devtools-profiler-demo.now.sh/

**Pull request merged**
