### PR TITLE
docs: fix a grammatical error

### PR DESCRIPTION
**Pull request by stuymedova**

### CODE REVIEW

**Comment by mr-vaibh** [comment]
I think this PR is just a duplicate of this one -- #4184 
Please delete this one, as it seems redundant ~~~thanks

**Comment by harish-sethuraman** [comment]
> I think this PR is just a duplicate of this one -- #4184

4184 is this PR only right?

**Comment by mr-vaibh** [comment]
> > I think this PR is just a duplicate of this one -- #4184
> 
> 4184 is this PR only right?

oops! I meant 4183,
typos 😅

**Comment by harish-sethuraman** [comment]
They dont seem to be the same PR.

**Comment by gaearon** [comment]
This might be a stylistic disagreement, but the intended reading is "you can use state and use reducer", i.e. to read them as individual words. It's fairly common colloquially because "use useState" sounds weird.

**Pull request closed without merging**
