### PR TITLE
mention onload when dom size calc

### PR DESCRIPTION
**Pull request by holylander**
When working with images and trying to get its size on react, you may need to wait until it is loaded by the browser, in order to get the correct size.

### CODE REVIEW

**Review by eps1lon — CHANGES_REQUESTED** [review]
I think this would be a perfect example for when a component resizes in the next paragraph. I don't think this section of the docs needs to document each possible workaround for observing element size changes.

**Comment by holylander** [comment]
thanks @eps1lon. Im not 100% sure If I understood you well :) Where should I move this comment then? Or shall we just abandon the change? thanks !

**Comment by eps1lon** [comment]
Check out the next paragraph that talks about the problem in general:

> In this example, the callback ref will be called only when the component mounts and unmounts, since the rendered `<h1>` component stays present throughout any rerenders. If you want to be notified any time a component resizes, you may want to use [`ResizeObserver`](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) or a third-party Hook built on it.

Your paragraph describes a more specific case. Talking about the specific and then general case is backwards in my opinion. 

I'm not familiar with the problem space itself so using ResizeObserve for layout shifts due to image loading may be overkill. Though I don't think this documentation is a good place to talk about all the possible approaches to detecting that an element's dimensions changed.

**Comment by holylander** [comment]
Makes sense. I have move the `onload` question to the paragraph that contains the example usecase ;)

**Pull request closed without merging**
