### PR TITLE
Take system's theme for the beta site

### PR DESCRIPTION
**Pull request by harish-sethuraman**
If the user has dark theme as preferred color scheme. apply dark mode.

It was a todo in the code 😄 
// TODO: respect system pref

### CODE REVIEW

**Comment by gaearon** [comment]
This won't work for the initial render. It will flash.

**Comment by harish-sethuraman** [comment]
Shall I add an IIFE to the document then? Like you had done in over reacted site? https://github.com/gaearon/overreacted.io/blob/master/src/html.js#L21
and then preserve it in the local storage?

**Comment by gaearon** [comment]
Seems like this doesn’t work for sandboxes?

**Comment by harish-sethuraman** [comment]
Do you mean for the sandpack component in the site? 🤔

**Comment by gaearon** [comment]
Oh I see. That's in https://github.com/reactjs/reactjs.org/pull/4019. We need to figure out what to get in first.

**Comment by gaearon** [comment]
When I load a preview on this branch with initial Dark more, I see the toggle flash.

**Comment by gaearon** [comment]
What's happening here is that the SSR content always assumes the theme is light. You should either hide the toggle or show the correct toggle icon with CSS.

**Comment by harish-sethuraman** [comment]
Will work on it and push changes for toggle.

**Comment by gaearon** [comment]
I think I'll take it over from here. Thanks!

**Comment by gaearon** [comment]
thanks!

**Pull request merged**
