### PR TITLE
Fix hero buttons to be clickable

### PR DESCRIPTION
**Pull request by sophiebits**

### CODE REVIEW

**Comment by sophiebits** [comment]
@webdesserts Seem good to you? (Review with ?w=1, it's really just a 2-line change.) Changing to relative means its effective z-index is above its absolutely positioned previous sibling.

**Comment by sophiebits** [comment]
Verified it works on the live preview. Gonna merge this for now to fix the site.

**Comment by webdesserts** [comment]
@sophiebits ahh, yeah that works. Sorry for the trouble!

**Comment by bvaughn** [comment]
Thank you for the fix, Sophie

**Comment by mjackson** [comment]
This was my fault. I should've done a more thorough review than just making sure the SVG *looked* ok. Thanks for the quick fix, Sophie.

**Comment by sophiebits** [comment]
No worries, I think it's easy to miss.

**Pull request merged**
