### PR TITLE
Fixed a minor typo in a comment

### PR DESCRIPTION
**Pull request by miosher**

### CODE REVIEW

**Review by eps1lon — APPROVED** [review]
Thanks, would you be so kind and sign the contributor license agreement? Otherwise I can't merge this PR.

**Comment by miosher** [comment]
@eps1lon Sure. I wanted to sign in but I got an error that the email I was using for signing is already associated with a different GitHub login. This is probably because I had once made a contribution using a different GitHub username registered under the same email (I had updated my GitHub username). I sent an email  to cla@fb.com with the issue.

**Review by klsingh016 — APPROVED** [review]
excellent

**Review by iamdevvalecha — APPROVED** [review]

**Comment by eps1lon** [comment]
@miosher Thanks!

**Pull request merged**
