### PR TITLE
A course learn page built in React JS

### PR DESCRIPTION
**Pull request by ulearnpro**
A course learn page is completely built on React JS 16.9, with nested component structure and rendering various files such as video, audio, pdf through axios

### CODE REVIEW

**Comment by ulearnpro** [comment]
Kindly merge this PR, it would be helpful for many developers

**Comment by alexkrolick** [comment]
The link is the same as the previous entry, please fix so someone can verify the content

**Comment by ulearnpro** [comment]
Sorry I couldn't get you. Could you please explain me in details

**Comment by alexkrolick** [comment]
Screen Shot 2019-08-28 at 22 12 09

This link should not be the same URL as the previous item - this looks like a mistake.

**Comment by ulearnpro** [comment]
Sorry, it's my mistake.. Now the URL is changed, please check and merge it..

**Comment by ulearnpro** [comment]
Team kindly merge this pull request

**Comment by ulearnpro** [comment]
Team, please merge my code

**Comment by lex111** [comment]
@ulearnpro thanks!

**Pull request merged**
