### PR TITLE
Fixes #25 - added warning to documentation

### LINKED ISSUE #25: Document that you can't rely on React 16 SSR patching up differences
This issue was originally filed by @Tarnadas at facebook/react/issues/10591. There's a lot of interesting discussion there. This is my (@bvaughn) attempt to summarize based on a [recent comment](https://github.com/facebook/react/issues/10591#issuecomment-334500962) by @dustinsoftware:

The [React 16 blog post](https://reactjs.org/blog/2017/09/26/react-v16.0.html) calls out that mismatches are not recommended, but indicates that some changes are OK (e.g. timestamps). This page, and the React docs, could be updated to point out that it's dangerous to have missing nodes on the server render, and they might get re-created with incorrect attributes.

### PR DESCRIPTION
**Pull request by fumblehool**
* Fixes #25

### CODE REVIEW

**Comment by bvaughn** [comment]
Maybe @sebmarkbage (or someone else that has more context on SSR+hydration) can review this PR to make sure it's sufficient.

**Comment by dustinsoftware** [comment]
Thanks! This warning is what I had in mind :)

**Comment by sebmarkbage** [comment]
It's a bit confusing wording because the missing nodes won't get the wrong attributes, it's the other nodes that might get the wrong attributes if one sibling is missing.

**Comment by bvaughn** [comment]
Thanks for weighing in @sebmarkbage. Would this be an improvement?

> However, it's dangerous to have missing nodes on the server render as this might cause sibling nodes to be created with incorrect attributes.

**Comment by sebmarkbage** [comment]
Sounds good

**Comment by bvaughn** [comment]
Cool beans. Changed in 8acec80. Thanks again!

**Pull request merged**
