### PR TITLE
Link accessible only on Open Networks.

### PR DESCRIPTION
**Pull request by arshita-kakkar**
Added a note under  : "If you haven't worked with JavaScript in the last few years, [these three points]..." as the link given (https://gist.github.com/gaearon/683e676101005de0add59e8bb345340c) works only on Open Networks and is inaccessible on Organizational Networks.

### CODE REVIEW

**Comment by alexkrolick** [comment]
Do you mean that your organization's firewall is blocking GitHub gists?

**Comment by arshita-kakkar** [comment]
Yes. The link won't work when firewalls are enabled by organization.
Error message : "This site can’t be reached The webpage at https://gist.github.com/gaearon/683e676101005de0add59e8bb345340c might be temporarily down or it may have moved permanently to a new web address."
ERR_TUNNEL_CONNECTION_FAILED

**Comment by alexkrolick** [comment]
OK, that's not something that would affect everyone - maybe you can discuss unblocking GitHub gists with your administrator?

**Comment by kambleaa007** [comment]
Does #Infosys blocks github gists, Its bad,
you can try, using your cellular network to access,
If its really urgent.

**Pull request closed without merging**
