### PR TITLE
Remove ReactWeek from Conference list

### PR DESCRIPTION
**Pull request by jcreighton**
Removes ReactWeek from Conference list.

### CODE REVIEW

**Comment by AlexWayfer** [comment]
> Accepting because of CoC violations.

I'm sorry, which ones?

**Comment by threepointone** [comment]
https://twitter.com/adamklein500/status/1110568867166851072

**Comment by AlexWayfer** [comment]
> https://twitter.com/adamklein500/status/1110568867166851072

I see apologies, but not violated points from the [Reactjs.org Code of Conduct](https://code.fb.com/codeofconduct/).

**Comment by threepointone** [comment]
I'm assuming you're asking in good faith, hence answering.  
this section in the CoC 
image
which were specifically apologised for
image

Feel free to reach out if you have a personal stake in this, happy to discuss privately. Else, hope we can move on from this.

**Comment by gaearon** [comment]
I’d like to emphasize that the Conferences and Meetups list on the React website is, and has always been moderated. We reserve the right to choose which events to put in the spotlight on our website.

When we can’t in good conscience be confident that an event meets the standards that other React events live up to, we may choose to stop listing it. We may later choose to put it on the list again if we have a good understanding that the organizers are serious about fostering an inclusive atmosphere at their events.

You are welcome to create your own list of conferences if you disagree with our editorial decisions.

**Comment by Ptico** [comment]
Sorry, just some questions to clarify:

1. From which time sex itself is taboo?

2. Should the people who had sex at least once be banned from attending the React conferences? 

3. Should the conferences provide dress code for attendees? How long the pants and dresses should be and which parts of body may be opened?

4. Which penance should apply to people who reject the Immaculate Conception? Especially in countries where auto-da-fé is prohibited by law

Thank you

**Comment by gaearon** [comment]
Your use of concern trolling and hyperbole doesn’t set us up for a productive conversation. However, I’ll try my best to answer.

There is no taboo about sex. There are many sex-positive people in the React community, and there is no problem with respectful discussions on these topics in appropriate places. That particular joke, however in poor taste it may be coming from an official conference account, is not the reason we unlisted the conference. (Although its wording does raise [concerns](https://mobile.twitter.com/dan_abramov/status/1110649492406038528) in the context of organizing a conference.)

Rather, the primary problem is in the way the organizers responded to criticism (for example, by doubling down with another “joke” about how men communicate more clearly than women — which is clearly disrespectful towards both speakers and attendees). Additionally, this was compounded by earlier reports we’ve received about the atmosphere at their events. The combination of these factors make us doubt the organizers can create a welcoming environment and enforce safe conduct at the conference.

Finally, as explained earlier, this is a curated list on our own website.
We reserve the right to add or remove events from it at our discretion.

I hope I answered your question.

**Comment by AlexWayfer** [comment]
> We reserve the right to add or remove events from it at our discretion.

Of course, there is no problem.

I just asked about:

> Accepting because of CoC violations.

It sounds like:

> Arrested because of laws violations.

I think, the reasons must be clear.

Also,

> This section in the CoC

isn't too concrete, it's can be replaced with a screenshot of the whole CoC, but OK.

---

> However, I’ll try my best to answer.

Thank you for the reply. I agree with "sexism jokes" (about communications) as reason.

**Comment by Ptico** [comment]
@gaearon Treating sarcastic satire as "trolling" (because this term makes its author looks offensive) is the same double standard, as removing for "Violation of CoC" while the true reason is "we don't like organizer, so GTFO, this is our list and we do what we want". (btw, this motivation is completely normal and I think everyone is ok with this)

Anyway, thanks for your answer. It's much more clear now. There are a lot of people puts a lot of effort organizing conferences, communities and meetups. Sending them a signal "don't be an asshole" is a good thing, but it requires a little bit more transparency, like you just did. Blaming one of organizers for violation of rules, which was not in fact violated, leads to demotivation and frustration for others. But this is easy way and I glad you choose another.

**Pull request merged**
