### PR TITLE
Fix scrolling to anchor with fixed menu

### PR DESCRIPTION
**Pull request by EPolovniy**
This request is clear version of https://github.com/reactjs/reactjs.org/pull/1855

### CODE REVIEW

**Comment by lex111** [comment]
@bdelrahmanrifai please review this. I would like to get your opinion on this.

**Comment by lex111** [comment]
@abdelrahmanrifai please review this. I would like to get your opinion on this.

**Comment by EPolovniy** [comment]
> I still not fully understand your solution, however it still not fixing the issue anyway. Check [the build from your PR](https://github.com/reactjs/reactjs.org/pull/1944#issuecomment-486164920)
> 
> Example: https://deploy-preview-1944--reactjs.netlify.com/docs/rendering-elements.html#rendering-an-element-into-the-dom
> 
> I adjusted my PR #1914 and it's working fine for all cases now.

@abdelrahmanrifai @lex111 
This code add hidden anchor for link. This anchor have absolute position given the height of the header.

It's working for all links.
In https://deploy-preview-1944--reactjs.netlify.com not working because this deploy was not cleaned .cache folder

**Comment by lex111** [comment]
> In deploy-preview-1944--reactjs.netlify.com not working because this deploy was not cleaned .cache folder

It' strange, try `force-push` to recreate the build of Netlify.

**Comment by EPolovniy** [comment]
> > In deploy-preview-1944--reactjs.netlify.com not working because this deploy was not cleaned .cache folder
> 
> It' strange, try `force-push` to recreate the build of Netlify.

Nothing changed

**Comment by EPolovniy** [comment]
@lex111 @abdelrahmanrifai 
Now in https://deploy-preview-1944--reactjs.netlify.com all work fine. If not working try clear browser cache

**Comment by lex111** [comment]
@EPolovniy there is a problem with `h4` :(

https://deploy-preview-1944--reactjs.netlify.com/docs/faq-functions.html#bind-in-constructor-es2015

**Comment by EPolovniy** [comment]
Fix issue with H4 but netlify not use new styles.

**Comment by lex111** [comment]
Please revert [this](https://github.com/reactjs/reactjs.org/pull/1944/commits/b831f50ce6cb417b200d782949e540b87fc77def)

**Comment by EPolovniy** [comment]
> Please revert [this](https://github.com/reactjs/reactjs.org/pull/1944/commits/b831f50ce6cb417b200d782949e540b87fc77def)

This changes make yarn check-all

**Comment by lex111** [comment]
However, this change doesn't apply to this issue. And besides, a new commit can restart Netlify.

**Comment by EPolovniy** [comment]
Done

**Comment by abdelrahmanrifai** [comment]
@EPolovniy I wonder why not just using CSS `::before` pseudo-element?

Also I think that `top: -10` for `h2` for example still depends on the calculation of the `marginTop` & `paddingTop` plus the header `hight`, so in the future it might be confusing for anyone trying to update any of these values.

**Comment by lex111** [comment]
Now everything works as it should. But I'm in doubt which PR to take :thinking:

**Comment by EPolovniy** [comment]
@lex111 My PR don't change UI :)

**Comment by abdelrahmanrifai** [comment]
@EPolovniy I could update my PR and make it don't change UI BTW! 😅

@lex111 It doesn’t matter which PR you'd take, as long as I will be able to navigate the docs without suffering from such an issue anymore!

**Comment by abdelrahmanrifai** [comment]
BTW, this PR changes the markup too, not sure how that might affect accessibility.

current
new

**Comment by lex111** [comment]
I like PR @abdelrahmanrifai because it is easier, so maybe it makes sense to finalize it so that the UI doesn't change?

@EPolovniy thank you for your time and effort. It seems to me that it is better to accept such a change that minimally affects the markup, and which just fixes this problem as simply as possible.

**Comment by EPolovniy** [comment]
image
I think this is a very bad decision on #1914 .

**Comment by EPolovniy** [comment]
And on reactjs.org
image

**Comment by abdelrahmanrifai** [comment]
@EPolovniy actually your PR still have some flaws:
https://deploy-preview-1944--reactjs.netlify.com/docs/accessibility.html#why-accessibility
https://deploy-preview-1944--reactjs.netlify.com/docs/accessibility.html#wcag

I just pushed a more simple robust solution in my PR #1914, check it out and give me your feedback!

**Pull request closed without merging**
