### PR TITLE
in solidarity with our community

### PR DESCRIPTION
**Pull request by threepointone**
https://twitter.com/kwuchu/status/1267436741692133376

While it would be great for us to do the same, I dunno how the team/fb comms feels about it. Opening this PR to discuss, and propose a plan B (in the PR) if that's not possible.

### CODE REVIEW

**Comment by threepointone** [comment]
It looks like the preview URLs aren't being generated. So here's a screenshot 

image

**Comment by threepointone** [comment]
To be clear, this PR is a backup plan. Ideally we should take it offline for a while, imo.

**Comment by Wilto** [comment]
image

**Comment by Wilto** [comment]
Then again, I suppose I’m not saying anything the project doesn’t already know, am I.

**Comment by threepointone** [comment]
Hi 👋 I'm sorry I can't do more.

**Comment by Daniel15** [comment]
Thanks for doing this! I submitted a PR to add a similar banner to the Relay site.

**Pull request merged**
