### PR TITLE
Added React Week '19 NYC

### PR DESCRIPTION
**Pull request by ManonMet**
We just launched our website!

### CODE REVIEW

**Comment by ManonMet** [comment]
Can you please let me know what you need to merge my pull request?

**Comment by lex111** [comment]
Resolve conflicts please.

**Comment by ManonMet** [comment]
@lex111 Done, thanks!

**Comment by ManonMet** [comment]
@lex111 What else can I do to merge my pull request?

**Comment by lex111** [comment]
@ManonMet sorry, I'm unfortunately forbidden to merge PR :(

**Pull request merged**
