### PR TITLE
Allow page zooming/scaling

### PR DESCRIPTION
**Pull request by lex111**
We need to allow page content scaling/zooming, since it is essential to users with low vision, for example.

### CODE REVIEW

**Comment by gaearon** [comment]
Can we do this but disable the iOS built-in “zoom into the sandbox on click” behavior somehow?

**Comment by lex111** [comment]
Yes, this can be achieved, but then code in sandboxes will be increased to 16px (only in which case iOS will not scale a page), see https://stackoverflow.com/questions/11064237/prevent-iphone-from-zooming-form for more details (it's the old question, but mentioned solution still works). See also https://twitter.com/joshwcomeau/status/1379782931116351490?s=12

**Comment by gaearon** [comment]
Btw what devices does this actually disable zooming on?

**Comment by lex111** [comment]
At the very least, this applies to Android users. And in general, it is not recommended to disable page scaling, it is bad in terms of a11y.

**Comment by gaearon** [comment]
> I have tested it on an iPhone 12, but anyway it is not recommended to disable page scaling, it is bad in terms of a11y.

I’m asking because I’m able to pinch the existing site (iPhone 11). So I want to be sure which interaction exactly we’re fixing.

**Comment by lex111** [comment]
This solution should work well on iPhone 11 too. As mentioned earlier, it's possible to increase font size only for focus state to prevent browser zooming in iOS, then font size in sandboxes will keep same as it in the current production version if you want. (Probably not many people will edit code in sandbox.)

**Comment by gaearon** [comment]
Sorry, I wasn't clear. I want to understand what exact scenario this PR is trying to fix by changing the meta tag. I know the meta tag says it's not scalable, but I'm able to zoom it on iOS just fine already. So I want to know what is the actual thing that's currently broken on the main branch.

**Comment by lex111** [comment]
The problem is that on Android devices at the moment doesn't work zooming/scaling, an that's what I want to fix in the current PR.

**Pull request merged**
