### PR TITLE
Document setting initial state with class property

### PR DESCRIPTION
**Pull request by ligaz**
Document initial state initialization with class property.
Add notes about its experimental syntax.

### CODE REVIEW

**Comment by gaearon** [comment]
I don’t think this is a good place to put it. This page is about React *without* modern syntax. We only mention ES6 version here as a reference point for comparison, but don’t actually want to show more modern syntax on this page. Does that make sense?

**Comment by ligaz** [comment]
It makes sense but this is the first page that I ended up while trying to find is this already documented. Actually once I issue the PR I found out that it is  in `react-without-es6.md`.

Here is my workflow:
* Go to [https://reactjs.org](https://reactjs.org/).
* Type state in the search box.
* Look at the results:
screen shot 2018-02-16 at 17 51 49

* Click on `Setting the Initial State` because this is exactly what I'm interested in. 

Should I move this into `state-and-lifecycle.md`?

**Comment by ligaz** [comment]
@gaearon How should we proceed with this one?

**Comment by alexkrolick** [comment]
There's already a PR to add that to State and Lifecycle: https://github.com/reactjs/reactjs.org/pull/557/files

Let's run with that one.

**Comment by ligaz** [comment]
@alexkrolick This PR #557 does not have an example and according to guidelines it should mention that class properties is an experimental feature.

**Comment by alexkrolick** [comment]
Correct, that's why it hasn't been merged. Feel free to collaborate.

**Pull request closed without merging**
