### PR TITLE
Link to relevant forwardRef docs

### PR DESCRIPTION
**Pull request by Vinnl**

### CODE REVIEW

**Comment by Vinnl** [comment]
The link can be seen here: https://deploy-preview-2229--reactjs.netlify.com/docs/hooks-reference.html#useimperativehandle

**Comment by lex111** [comment]
Correct link should be https://reactjs.org/docs/react-api.html#reactforwardref

**Comment by Vinnl** [comment]
Thanks @lex111, that makes more sense indeed - fixed.

**Comment by threepointone** [comment]
Thanks!

**Pull request merged**
