### PR TITLE
fix outline in sideBar button

### PR DESCRIPTION
**Pull request by israelKusayev**
fix outline button in small devices.

image

### CODE REVIEW

**Comment by ahtee** [comment]
What browser and device are you using? I am not seeing an outline on the live version of the site on safari or chrome on iOS.

**Comment by israelKusayev** [comment]
I'm using chrome
And I have galaxy s10

**Comment by israelKusayev** [comment]
Any comments?

**Comment by ahtee** [comment]
If im not mistaken, the outline offered by the browser is there for accessibility purposes. 
More reading: https://a11yproject.com/posts/never-remove-css-outlines/

**Comment by alexkrolick** [comment]
Correct, it should not be removed

**Pull request closed without merging**
