### PR TITLE
Code of conduct

### PR DESCRIPTION
**Pull request by alocke12992**

### CODE REVIEW

**Comment by alocke12992** [comment]
Note that this issue exists on all of the fbOpensource projects. The "Code of Conduct" link is broken.

**Comment by gaearon** [comment]
Thanks for reporting. We should fix the link.

**Comment by zpao** [comment]
Just a heads up: code.facebook.com migrated today to code.fb.com. We lost a couple pages along the way. I'll be recreating the code of conduct on opensource.fb.com as a replacement shortly, will update here when that's up.

**Comment by zpao** [comment]
Eh, I just made https://code.fb.com/codeofconduct/ instead. Takes the pressure off moving this into your own docs. I'll probably make that old link redirect to a different location at some point, it's just a bit more work right now.

**Comment by gaearon** [comment]
Thanks for fixing the link @zpao!

**Pull request closed without merging**
