### PR TITLE
[Beta] Add bundle analyzer

### PR DESCRIPTION
**Pull request by gaearon**
This adds `yarn analyze` command so that we can start looking at the bundle size and how to improve it.
If someone knows how to hook this up to GH actions to see a diff on each PR let me know!

### CODE REVIEW

**Comment by harish-sethuraman** [comment]
I came across this GH action that lists PR's impact on the bundle size. 
https://github.com/hashicorp/nextjs-bundle-analysis/  
shall we try this out? 

Or should we make use yarn analyze during PR builds and make use of the html inside the analyze directory generated in the build?

**Comment by gaearon** [comment]
Hmm. I tried this but for some reason it ignores my `working-directory` setting and works from root.
https://github.com/reactjs/reactjs.org/runs/4126582048?check_suite_focus=true

**Comment by harish-sethuraman** [comment]
Did you try running a cd beta and then commands ?

**Comment by gaearon** [comment]
No, it looks like `cd` is isolated between steps.

**Comment by harish-sethuraman** [comment]
I'll create a repo and raise the fix.

**Comment by harish-sethuraman** [comment]
Nice work! BTW we should close and re open PR for the workflow to run right ?

**Comment by gaearon** [comment]
you need to rebase if you have an older PR

**Pull request merged**
