### PR TITLE
docs: Adding Social Banner in Support of Ukraine

### PR DESCRIPTION
**Pull request by dmitryvinn-fb**
## Summary
Our mission at [Meta Open Source](https://opensource.facebook.com/) is to empower communities through open source, and we believe that it means building a welcoming and safe environment for all.  As a part of this work, we are adding this banner in support for Ukraine during this crisis.

*Note:* As a part of this work, I made a better distinction between Social banner which is more permanent element and Survey banner which is a part of temporary campaign that folks can dismiss.

## Testing
image

image

image

### CODE REVIEW

**Review by rickhanlonii — APPROVED** [review]
🇺🇦

**Comment by dmitryvinn-fb** [comment]
Can anyone please help deciphering the lint errors? I can't figure out what I might have done wrong with formatting

**Comment by harish-sethuraman** [comment]
Try `yarn format:source` in the repo's root folder

**Comment by dmitryvinn-fb** [comment]
Thank you - I just passed --check flag in a prettier command and found what the issue was. Had to format several files. Updating the PR now

**Comment by dmitryvinn-fb** [comment]
Alrighty, it's good to go! We already added this banner to Jest, and working on other projects as we speak

**Comment by dushaobindoudou** [comment]
Open source projects should remain neutral，very disappointed

**Comment by zjp1300** [comment]
It is not a good behavior for open source software to participate in political struggle. Please understand the meaning of open source.

**Comment by jeffie** [comment]
Open Source Without Borders... joke

**Pull request merged**
