### PR TITLE
added stackblitz to playground

### PR DESCRIPTION
**Pull request by devpato**
Stackblitz supports ReactJS as a playground. 

https://stackblitz.com/fork/react

### CODE REVIEW

**Comment by EricSimons** [comment]
@devpato yay! Awesome work 👏 Perhaps you could change the link to point at `https://stackblitz.com/fork/react`? That should ensure anyone clicking that link lands on a fresh React project. Other than that LGTM!

**Comment by devpato** [comment]
> @devpato yay! Awesome work 👏 Perhaps you could change the link to point at `https://stackblitz.com/fork/react`? That should ensure anyone clicking that link lands on a fresh React project. Other than that LGTM!

done :)

**Comment by devpato** [comment]
Hi! I'm curios. when is this going to be merged? Or do I need to do something else on my side. Thanks :)

**Comment by threepointone** [comment]
merged this by mistake, sorry. I think we're comfortable with our current recommendations.

**Comment by EricSimons** [comment]
@threepointone considering I created the initial PR that enabled y'all to continue using codepen (https://github.com/reactjs/reactjs.org/pull/245), might the team be open to reconsidering this decision to ensure there's no signaling of favoritism in the community?

**Comment by threepointone** [comment]
Yeah I thought about this more and have reconsidered, and I apologise for removing it. Let me revert my revert :)

**Comment by threepointone** [comment]
https://github.com/reactjs/reactjs.org/pull/2821 sorry again!

**Comment by EricSimons** [comment]
No worries at all! Thank you for all the hard work you & the team do to make React great ❤️

**Pull request merged**
