### PR TITLE
docs: revert "docs: Adding Social Banner in Support of Ukraine (#4397)"

### PR DESCRIPTION
**Pull request by xcatliu**
This reverts commit d90fd21fdbedb075a4cc196c16156b534daf14a4.

### CODE REVIEW

**Comment by rottenpen** [comment]
lgtm

**Review by ycjcl868 — APPROVED** [review]

**Review by undefined-moe — APPROVED** [review]

**Review by Shigma — APPROVED** [review]

**Review by simon300000 — APPROVED** [review]

**Review by XxLittleCxX — APPROVED** [review]

**Review by shugen002 — APPROVED** [review]

**Review by fireairforce — APPROVED** [review]

**Review by maxesisn — APPROVED** [review]

**Review by ulivz — APPROVED** [review]

**Review by TheSnowfield — APPROVED** [review]

**Review by MaikoTan — APPROVED** [review]

**Review by yanyongyu — APPROVED** [review]

**Review by xh321 — APPROVED** [review]

**Review by NWYLZW — APPROVED** [review]

**Review by Anillc — APPROVED** [review]

**Review by giflee — APPROVED** [review]

**Review by wdvxdr1123 — APPROVED** [review]

**Review by rlzzj — APPROVED** [review]

**Review by lonelyion — APPROVED** [review]

**Review by SoMall-dumpling — APPROVED** [review]

**Review by StarHeartHunt — APPROVED** [review]

**Comment by jks15satoshi** [comment]
Make technology politicalized would never be accepted.

**Review by AcceNoi — APPROVED** [review]

**Review by BalconyJH — APPROVED** [review]

**Comment by dbFlower** [comment]
已收到

**Review by lrvy — APPROVED** [review]

**Review by chilingling — APPROVED** [review]
Please, Technology should not be politicized.

**Review by CHOYSEN — APPROVED** [review]

**Review by kirainmoe — APPROVED** [review]

**Review by Meriky — APPROVED** [review]

**Review by hongcyu — APPROVED** [review]

**Review by mobyw — APPROVED** [review]

**Comment by lwyj123** [comment]
@rickhanlonii https://github.com/facebook/react/issues/23402

**Review by ch3cknull — APPROVED** [review]

**Review by andywang425 — APPROVED** [review]

**Review by idlist — APPROVED** [review]

**Comment by rickhanlonii** [comment]
Please see https://github.com/facebook/react/issues/23402#issuecomment-1058227670.

**Pull request closed without merging**
