### PR TITLE
Fix missing closing braces in code samples

### PR DESCRIPTION
**Pull request by fuchodeveloper**
Fixed the closing braces for the code samples at https://reactjs.org/docs/lifting-state-up.html#lifting-state-up

### CODE REVIEW

**Comment by gaearon** [comment]
These aren't missing braces, they just show a part of the code.
Maybe we can add

```js
// ...
```

instead?

**Comment by fuchodeveloper** [comment]
Ok.
Adding
`// ...`
That would be great.

**Comment by gaearon** [comment]
Mind making the change? Thanks!

**Comment by fuchodeveloper** [comment]
Effected the change

**Comment by gaearon** [comment]
Seems like we fixed this in https://github.com/reactjs/reactjs.org/pull/115.

**Pull request closed without merging**
