### PR TITLE
Updates CrowdIn configuration to use /docs/lang/folder/file.md

### PR DESCRIPTION
**Pull request by ericnakagawa**
This PR changes where localized files, downloaded from CrowdIn, are output.

To verify you can run crowdin upload and download locally from reacjs.org folder:

crowdin --config crowdin.yaml upload sources --auto-update -b test-17
crowdin --config crowdin.yaml download -b test-17

The files will then be available in reactjs.org/docs/*.

### CODE REVIEW

**Comment by bvaughn** [comment]
Thanks Eric.

**Comment by bvaughn** [comment]
cc @clemmy We'll want to merge this into our crowdin integration branch.

**Comment by clemmy** [comment]
Yup, we can probably just merge master in. I'll submit a PR.

**Comment by clemmy** [comment]
@ericnakagawa I built and downloaded the translation zip, and I see 3 folders after extracting: `master`, `test-16`, and `test-17`. Looking at the contents of each one: `master` looks recursive, which isn't what we want, and the contents of `test-17` seem to be more aligned with what I was expecting, but it only has `blog` and `docs` folder underneath a locale directory. (Also the contents are in English). Is this what is expected, or am I doing something wrong?

**Comment by clemmy** [comment]
screen shot 2017-11-19 at 8 54 46 pm

**Pull request merged**
