### PR TITLE
Improves the documentation on Reconciliation

### PR DESCRIPTION
**Pull request by rosenfeld**
This is the same pull request as https://github.com/facebook/react/pull/9994 backported to this project as requested by @bvaughn. Thanks.

### CODE REVIEW

**Comment by rosenfeld** [comment]
More specifically: https://deploy-preview-108--reactjs.netlify.com/docs/reconciliation.html#tradeoffs

**Comment by rosenfeld** [comment]
Thanks, that makes me much more confident about using React (or React-like libraries) regarding third-party components integration :)

**Comment by gaearon** [comment]
I'm not a big fan of adding things in parens that disrupt the flow of the paragraph. These always looked like they're tacked on by somebody else 😛 Try to read it aloud—by the time I get to the last sentence I get a bit lost.

Can you maybe send a follow up PR that restructures this paragraph to look like it was written organically by a single person? Maybe by splitting it into two paragraph or shuffling the sentences around.

Thanks!

**Comment by rosenfeld** [comment]
Sure, you're right. I'll follow up with a new PR.

**Comment by rosenfeld** [comment]
done

**Pull request merged**
