### PR TITLE
docs: class properties and object spread are no longer experimental

### PR DESCRIPTION
**Pull request by bioub**
Theses pages refers to Class Properties as a Stage 3 Proposal or as experimental which is no longer the case since it's part of the ES2022 specification :

- [Passing Functions to Components](https://github.com/reactjs/reactjs.org/blob/a4d4893bd3c56f4f7f821c46ed512eac6c3c21b9/content/docs/faq-functions.md)
- [Handling Events](https://github.com/reactjs/reactjs.org/blob/a4d4893bd3c56f4f7f821c46ed512eac6c3c21b9/content/docs/handling-events.md)
- [Introducing Hooks](https://github.com/reactjs/reactjs.org/blob/a4d4893bd3c56f4f7f821c46ed512eac6c3c21b9/content/docs/hooks-intro.md)
- [React Without ES6](https://github.com/reactjs/reactjs.org/blob/a4d4893bd3c56f4f7f821c46ed512eac6c3c21b9/content/docs/react-without-es6.md)
- [Typechecking With PropTypes](https://github.com/reactjs/reactjs.org/blob/a4d4893bd3c56f4f7f821c46ed512eac6c3c21b9/content/docs/typechecking-with-proptypes.md)

The tutorial still refers to Object Spread as a proposal which is no longer the case since ES2018 : 

- [Tutorial](https://github.com/reactjs/reactjs.org/blob/a4d4893bd3c56f4f7f821c46ed512eac6c3c21b9/content/tutorial/tutorial.md)

### CODE REVIEW

**Review by eps1lon — APPROVED** [review]
Makes sense, thanks!

**Comment by eps1lon** [comment]
Could you rebase onto `main` to try to fix the Vercel build error? Looks like flake but just to be sure.

**Comment by bioub** [comment]
@eps1lon done !

**Review by eps1lon — APPROVED** [review]
Thanks!

**Pull request merged**
