### PR TITLE
[Early Preview] New React Documentation

### PR DESCRIPTION
**Pull request by nearestnabors**
Since [announcing the start of the new React documentation effort](https://github.com/reactjs/reactjs.org/issues/3308), we’ve been busy writing the content and building a custom website designed around the learning experience. We are now ready to share this early preview of what we’ve created so far to get your feedback.

**This early preview is deployed at [beta.reactjs.org](https://beta.reactjs.org/) and is in active development.**

**Please leave any feedback in https://github.com/reactjs/reactjs.org/issues/3308.**

## TLDR

Visit the early preview of the new React Docs at [beta.reactjs.org](https://beta.reactjs.org/) to find:

* All new learning materials featuring Hooks
* Interactive examples and challenges
* “Code diagrams” that visually dissect how Hooks work
* Illustrations and diagrams that explain how React works
* New site designed around learning experience

You may encounter some broken links—pardon our dust! Some content is yet to be released!

## What's in the beta

The beta has two major sections:

* [**Learn React**](https://beta.reactjs.org/learn)**—a comprehensive, step-by-step guide to React.** This section is roughly 70% complete. This content is stable and unlikely to change much beyond a few edits and fixes. Some content is still being written (notably, guides for effects, performance optimizations, and React DevTools). 
* **[API Reference](https://beta.reactjs.org/reference)—detailed explanations of each API** This section currently only has a few pages, so there is a lot left to write here! Have a look at the [`useState`](https://beta.reactjs.org/reference/usestate) page to get a sense of what’s coming.

The landing page is a temporary stub and will be replaced closer to the end of the project. Similarly, the **Home** tab is a bit empty now—we intend to port over more things from the existing site, like Blog, after most of the remaining work is done.

### Known issues

* **No tutorials.** We need to complete explanations for all core concepts and APIs before we can add tutorials. (This could be really cool to work on with the community at a later date! But not today!)
* **Performance.** When we say “beta,” we mean the site as well as the content! We still have some perf optimizations to make like code splitting at a later stage.
* **Accessibility.** While we have been mindful of accessibility during production, we’re waiting until the site is close to getting out of beta to run a comprehensive accessibility audit.

## What’s next

We will make an official post on the blog and put up a banner on the existing site to let visitors know where to find the new docs sometime after gathering feedback from this soft launch. 

Once we achieve content parity with the old site, we’ll be ready to switch over to this one and keep the old one archived at a subdomain. We'll figure out which pages to redirect to which site at that stage—for now it's too early to discuss a plan. We intend to document all the stable React APIs before we switch over. That includes classes—however, they will be described on a separate page, while most of the docs will use Hooks.

Please note that:

* We are not ready to kick off any official translation efforts at this time because the content is still in a state of flux. **(Update: we're kicking them off in https://github.com/reactjs/reactjs.org/issues/4135.)**
* To keep the tone cohesive, we are writing the primary new content ourselves. While offers to write are much appreciated, we must regretfully decline for now!

## You can help!

* **Read and share** the docs with friends, colleagues, family!
* **Report bugs!** If you see one, please don’t hesitate to leave a comment here or send a fix to the `beta` folder in the `main` branch with the `[Beta]` tag in the title.
* **Tell us** what you think!

## Where to leave feedback?

* Leave your general feedback in a comment in https://github.com/reactjs/reactjs.org/issues/3308 or using [this handy survey](https://www.surveymonkey.co.uk/r/Y6GH986).
* Leave feedback as you read using the feedback button on the site

High-level feedback is more useful than e.g. typos since we'll be doing more editing passes on all the content (bug fixes for typos much appreciated!). We'd particularly appreciate feedback on how to organize the content (see https://github.com/reactjs/reactjs.org/pull/3965#issuecomment-949262481).

## Special thanks

Getting to this stage required a lot of effort from different people, whom we would like to thank and acknowledge. This includes:

* [Rachel Nabors](https://twitter.com/RachelNabors): editing, writing, illustrating
* [Dan Abramov](https://twitter.com/dan_abramov): writing, curriculum design
* [Sylwia Vargas](https://twitter.com/SylwiaVargas): example code
* [Dan Lebowitz](https://twitter.com/lebo): design
* [Razvan Gradinar](https://dribbble.com/GradinarRazvan): design
* [Maggie Appleton](https://maggieappleton.com/): diagram system (not integrated yet)
* [Jared Palmer](https://twitter.com/jaredpalmer): site development
* [ThisDotLabs](https://www.thisdot.co/) ([Dane Grant](https://twitter.com/danecando), [Dustin Goodman](https://twitter.com/dustinsgoodman)): site development
* [CodeSandbox](https://codesandbox.io/) ([Ives van Hoorne](https://twitter.com/CompuIves), [Alex Moldovan](https://twitter.com/alexnmoldovan), [Jasper De Moor](https://twitter.com/JasperDeMoor), [Danilo Woznica](https://twitter.com/danilowoz)): sandbox integration
* [Rick Hanlon](https://twitter.com/rickhanlonii): site development

We'd also like to thank countless alpha testers and community members who gave us feedback along the way. Your support and encouragement meant the world to us over this longhaul project!

### CODE REVIEW

**Comment by weyert** [comment]
You have included an API key in this PR

**Comment by gaearon** [comment]
@weyert

>You have included an API key in this PR in one of your config files

Do you mind sharing which one? I assume it's probably intentional, e.g. Algolia needs one for search. Feel free to mail me `<my username>@fb.com` if there's something I overlooked.

**Comment by gaearon** [comment]
@timdorr 

>It looked rather barren to me. I don't know if it's the tab design, but it was non-obvious that the majority of the content I'm looking for is behind that Learn tab.

It has very little content now, but we will later move Blog and a few other things there. So it seems a bit premature to restructure before we know how the rest of the things will look together, as we might have to split it back up. I will clarify this in the post.

**Comment by gaearon** [comment]
No worries, appreciate the diligence :)

**Comment by mochi-sann** [comment]
## Future Request

On a small screen like a smartphone, the line numbers overlap with the body of the code when scrolling horizontally, so I think the background of the line numbers should be colored.

https://user-images.githubusercontent.com/44772513/138385266-00b3d47d-ff0d-4901-894f-f30f6bb76892.MP4

**Comment by gaearon** [comment]
>On a small screen like a smartphone, the line numbers overlap with the body of the code when scrolling horizontally, so I think the background of the line numbers should be colored.

Oops. Pretty sure I broke it ... today. Thanks.

**Comment by valtism** [comment]
So happy this has landed 💙💙💙

Just noticed that with a mouse plugged in (macOS, Safari 15.4), the nav scrollbar is white. I don't know why this is the case, because when the content expands to fill more than 100vh it disappears and is dark again.

image

Also, dark mode selection does not persist. Would like it to be stored in localstorage or something.

**Comment by valtism** [comment]
Also, I can guess this may be in the works, but I'd love for the code (blocks as well as editable sections) to have a dark mode variant.

image

**Comment by nickmccurdy** [comment]
Personally I like the new page structure, though the blog feels a bit out of place in the sidebar. Perhaps it should be its own tab like the other three sections.

**Comment by gaearon** [comment]
We're kicking off the translation process in https://github.com/reactjs/reactjs.org/issues/4135.

**Pull request merged**
