### PR TITLE
Fixes outline style in Section

### PR DESCRIPTION
**Pull request by suyalcinkaya**
Fixes:
issue image

### CODE REVIEW

**Comment by kevjin** [comment]
@lex111 just randomly came across this PR, but personally I think having no outline looks better. I can understand why it would be there for accessibility purposes though, especially for users navigating the website on a keyboard.

**Comment by lex111** [comment]
@kevjin I understand this, but just here accessibility is of great importance.

**Comment by suyalcinkaya** [comment]
Because it looks much better visually without the outline? :)

**Comment by threepointone** [comment]
The outline is an accessibility concern, and doesn't affect visually atypical readers. Thanks for the PR!

**Pull request closed without merging**
