### PR TITLE
Add Reactathon 2018 Conf

### PR DESCRIPTION
**Pull request by dunphyben**
This adds Reactathon 2018 to the list of Conferences:

image

### CODE REVIEW

**Comment by dunphyben** [comment]
Having a bit of difficulty signing the CLA. It says I'm already associated with an existing contributor. Unless there is something else going on, I'm guessing this is a result of submitting the PR from my github organization, [Real World React](https://github.com/realworldreact/reactjs.org)

Any advice or assistance is appreciated. 

image

**Comment by icarlossz** [comment]
If you have problems with the contributor agreement send a mail to cla@fb.com and comment on your problem.

**Comment by dunphyben** [comment]
Thanks @icarlossz. Request for support has already been initiated; just wanted to clarify on the PR as well.

**Comment by JoelMarcey** [comment]
@dunphyben I made a fix internally and the CLA bot should come by soon and be happy again. Hopefully :)

**Comment by eps1lon** [comment]
Thanks for your work. Looks like we forgot your PR and somebody else added the conference in the meantime.

**Pull request closed without merging**
