### PR TITLE
Fixed React syntax's in docs.

### PR DESCRIPTION
**Pull request by akgupta0777**
https://reactjs.org/docs/react-dom.html#render
https://reactjs.org/docs/react-dom.html#hydrate
https://reactjs.org/docs/react-component.html#setstate
has wrong syntaxes.
This PR fixes it.

### CODE REVIEW

**Comment by akgupta0777** [comment]
Please review @eps1lon @bvaughn.

**Comment by akgupta0777** [comment]
image

Is this intentional because I found them a lot in documentation.

**Comment by bvaughn** [comment]
I _think_ the former style _is_ intentional, to show that the 3rd argument itself (including the comma) is optional, but I agree it's confusing because it's not valid syntax. (Then again, even though the `[]` would be valid syntax, it's not a valid use either.)


I think maybe a better way for us to do this might be to follow [MDN's style](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#syntax), e.g.
> # Syntax
> ```js
> target.addEventListener(type, listener);
> target.addEventListener(type, listener, options);
> target.addEventListener(type, listener, useCapture);
> target.addEventListener(type, listener, useCapture, wantsUntrusted); // wantsUntrusted is Firefox only
> ```

**Comment by akgupta0777** [comment]
Using MDN's style is a lot of work. I think we can use a **_(underscore)** to represent those parameters that are optional.
For Example :
```
ReactDOM.render(element, container, _callback)
setState(stateChange, _callback)
ReactDOM.hydrate(element, container, _callback)
```
What do you think?

**Comment by bvaughn** [comment]
I think brackets are more intuitive (based on other API documentation I've seen). underscore means nothing to me.

**Comment by akgupta0777** [comment]
So should we use MDN style or leave it as it is?

**Comment by bvaughn** [comment]
No strong feelings. Maybe someone else has those.

**Comment by eps1lon** [comment]
I think we already had one or two PRs for this syntax. It's clear by now that it's confusing to a considerable amount because it almost looks like valid JS. 

The MDN style has the benefit that it uses valid JS even though we don't actually have function overloading. But I find MDN API docs extraordinary good and value consistent styles of API documentation. So I'm all for changing it to the MDN style.

But we should check every signature first and change all of them where necessary. And it's unclear if that's needed once https://github.com/reactjs/reactjs.org/issues/3308 lands so it might be work that's short lived.

**Comment by akgupta0777** [comment]
Thanks for checking this up. I think the best thing to do is to wait for the new reactjs site.

**Comment by harish-sethuraman** [comment]
We are changing the format in the new site. Thank you 😄 .

**Pull request closed without merging**
