### PR TITLE
Import HomepageHero component on index.md only

### PR DESCRIPTION
**Pull request by Charca**
# WIP~

### CODE REVIEW

**Comment by gaearon** [comment]
We can do this but it's not super sustainable. The problem is more general. What's a general solution to this?

**Comment by gaearon** [comment]
I think the proper solution would be to move to Server Components. Seems like we’re not too far off from being able to try that.

**Comment by Charca** [comment]
@gaearon I am not aware of a general solution that doesn't involve loading all components globally, unfortunately :/

Two options come to mind, but none of them are really general:
1. Dedicated sets of components for different layouts (i.e. `HomeLayout`, `APIRefenreceLayout`, `BlogLayout`, etc): this could be useful since there are a few components that are only used in the API reference pages, and others that are exclusive to the "learn" section, for example.
2. Use an mdx plugin that adds missing imports for JSX elements it finds in the document (I haven't explored this option too much, so this could be a terrible idea).

I'm not super familiar with Server Components, but if you think that's the way to go, that's really great to hear!

**Comment by Charca** [comment]
I'll close this PR now, it wasn't a super big improvement anyways. Thanks for the input!

**Pull request closed without merging**
