### PR TITLE
Add React UI Tools to Fee Components List

### PR DESCRIPTION
**Pull request by jnsencha**
:

### CODE REVIEW

**Comment by jnsencha** [comment]
@facebook-github-bot I can't sign the CLA, I am told my email is already associated with an account.

**Comment by jnsencha** [comment]
@reactjs-bot assistance please?

**Comment by jnsencha** [comment]
@benschwarz I'm not able to sign the CLA as I'm told it's already been signed using my email.

**Comment by lex111** [comment]
@jnsencha thanks!

**Comment by jnsencha** [comment]
Thanks @lex111 !!!

**Pull request merged**
