### PR TITLE
[beta] bump tailwind to v3 and update config

### PR DESCRIPTION
**Pull request by dammy001**

### CODE REVIEW

**Comment by gaearon** [comment]
nice, thanks!

seems like this widget is wrongly positioned:

Screenshot 2022-02-21 at 11 47 24

**Comment by dammy001** [comment]
@gaearon position fixed

**Comment by gaearon** [comment]
fonts look a bit bolder/blurrier than before. did some aliasing config change?

**Comment by dammy001** [comment]
@gaearon nope. Didn't notice that. i'll check now

**Comment by dammy001** [comment]
@gaearon i think we're good to go now

**Comment by gaearon** [comment]
looks good. thanks!

**Comment by gaearon** [comment]
looks good. thanks!

**Comment by harish-sethuraman** [comment]
https://tailwindcss.com/docs/upgrade-guide#automatic-transforms-and-filters
As per this section we might not actually want transform, filter, or backdrop-filter classes. But there are places where we have them like this

[reactjs.org/beta/src/components/Icon/IconArrow.tsx](https://github.com/reactjs/reactjs.org/blob/aeb17885d785306c4eb506fd93f5962aa2764fd9/beta/src/components/Icon/IconArrow.tsx#L22)

- https://github.com/reactjs/reactjs.org/blob/aeb17885d785306c4eb506fd93f5962aa2764fd9/beta/src/components/Icon/IconArrow.tsx#L22
Shall we evaluate if we really need those classes and remove them as part of migration?



@shamwela you want to look into this?

**Comment by shamwela** [comment]
> https://tailwindcss.com/docs/upgrade-guide#automatic-transforms-and-filters As per this section we might not actually want transform, filter, or backdrop-filter classes. But there are places where we have them like this
> 
> [reactjs.org/beta/src/components/Icon/IconArrow.tsx](https://github.com/reactjs/reactjs.org/blob/aeb17885d785306c4eb506fd93f5962aa2764fd9/beta/src/components/Icon/IconArrow.tsx#L22)
> 
> * https://github.com/reactjs/reactjs.org/blob/aeb17885d785306c4eb506fd93f5962aa2764fd9/beta/src/components/Icon/IconArrow.tsx#L22
>   
>   Shall we evaluate if we really need those classes and remove them as part of migration?
> 
> @shamwela you want to look into this?

I'll try to remove them in a new pull request.

**Pull request merged**
