### PR TITLE
Changed wording about UNSAFE_componentWillReceiveProps deprecation

### PR DESCRIPTION
**Pull request by bvaughn**
I tried to compress this a little bit. (It's still a lot of words to have in one of our yellow "notes".) I also removed the misleading deprecation bit.

### CODE REVIEW

**Comment by gaearon** [comment]
Maybe let's combine this with note at the bottom? And make that first?

Same for other methods.

screen shot 2018-12-06 at 5 51 12 pm

**Comment by bvaughn** [comment]
> Maybe let's combine this with note at the bottom? And make that first?

I don't mind moving the note near the bottom higher up, but I'm not sure "combining" them feels right. This is already a _lot_ of text for what (I think) is intended to be a short format note.

> Same for other methods.

Not sure what this means.

**Comment by gaearon** [comment]
I mean that other methods have the same note at the bottom and it’s very easy to miss. But arguably that’s the most important one and the one people most confused over.

**Comment by bvaughn** [comment]
Oh, so~ move those notes higher for each lifecycle? Sure, I'm not opposed to that.

**Comment by bvaughn** [comment]
Okay I moved those comment blocks higher up.

**Pull request merged**
