### PR TITLE
make code sample a little more concise

### PR DESCRIPTION
**Pull request by kaycebasques**
Just a little, opinionated suggestion. You can close this if it doesn't match your general code sample style.

### CODE REVIEW

**Comment by alexkrolick** [comment]
Someone else suggested the same thing recently: https://github.com/reactjs/reactjs.org/pull/655

I'm not a fan of reassigning a JSX subtree after it's been declared. How about taking another approach to clean up the block, like a ternary?

**Comment by EarthSchlange** [comment]
@alexkrolick An ternary approach more like this:
`let button = isLoggedIn ?  <LogoutButton onClick={this.handleLogoutClick} /> : <LoginButton onClick={this.handleLoginClick} />; `
to clean up the if else.

**Comment by alexkrolick** [comment]
Yes 👍

**Comment by alexkrolick** [comment]
Closed in favor of #686

**Comment by gaearon** [comment]
For future reference: https://github.com/reactjs/reactjs.org/pull/686#issuecomment-396097317

**Pull request closed without merging**
