### PR TITLE
Doc Updates Request - Adding JSitor as supported tool for trying ReactJS online

### PR DESCRIPTION
**Pull request by ashvin777**
Issue -
https://github.com/reactjs/reactjs.org/issues/2548

### CODE REVIEW

**Comment by ashvin777** [comment]
Please review.

**Comment by ashvin777** [comment]
Any update guys? This is a very short PR.

**Comment by ashvin777** [comment]
Can it be merged?

**Comment by alexkrolick** [comment]
We generally have waited for services like this to become established before linking to them. See previous commits for Codesandbox, Glitch.

**Comment by sophiebits** [comment]
Agree that JSitor isn't currently popular enough (to my knowledge) that we should list it here. Whenever possible, we want to link to community-standard tools that are well-maintained.

**Pull request closed without merging**
